### ISSUE TITLE
Feature Request: Add non-malignant neoplasms to cancer_type_code.

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#103]
After discussions with working group, decided we should accept non-malignant neoplasms as well. Comment from working group:

> "_I see no problem in listing non-malignant neoplasms as well. For some longitudinal cancer studies an early diagnosis of a precursor lesion and its genetic information might be highly relevant._"

Will update regex for following fields:
cancer_type_code
cancer_type_prior_malignancy

**Comment by rosibaj** [comment]
verified on production - was able to submit hte new `d` value code
