### ISSUE TITLE
🐛 Prevent data submitters from submitting ARGO IDs

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#107]
## Issue
The current regex for `submitter_donor_id`, `submitter_specimen_id` and `submitter_sample_id` do not prevent a data submitter from submitting an identifier that has the same prefix as ARGO reserved prefixes (ie. DO*, SP* and SA*). 

In ICGC, we had a script validation to prevent data submitters from using ICGC reserved prefixes. We can do the same, or modify the existing regex.

Exclude following prefixes:
`submitter_donor_id`: exclude `DO` prefix
`submitter_specimen_id`: exclude `SP` prefix
`submitter_sample_id`: exclude `SA` prefix
`submitter_treatment_id`: exclude `TR` prefix
`submitter_primary_diagnosis_id`: exclude `PD` prefix
`submitter_follow_up_id`: exclude `FU` prefix

**Comment by kcullion** [comment]
@rosibaj I tested these ids and it's working as expected. I can't enter any values that start with those prefixes
