### ISSUE TITLE
Rename central_pathology_confirmed and application_form fields

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#109]
Based on user feedback, there are two clinical fields that will require re-naming. The current clinical field names are confusing some data submitters. After discussions with working group, it was agreed to update the following:

central_pathology_confirmed -> reference_pathology_confirmed. Will also update description so it is more clear.
application_form -> radiation_therapy_type

**Comment by hknahal** [comment]
Feedback from working group leader:

> “central pathology review” is a common term, but if it causes trouble, one might say “reference pathology”. It only applies to clinical studies, where all pathological diagnoses are confirmed by one or a few (usually a single one) (central) reference pathologist.

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
