### ISSUE TITLE
Feature Request: Change "relapse" to "relapse or recurrence" in disease_status_at_followup codelist

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#111]
## Detailed Description

Beta-testers from the PACA-CA project were confused as to how to submit the `disease_status_at_followup` since apparently the term "relapse" is not used in pancreatic cancer (they use recurrence). 

Based on discussions with the working group, it was confirmed that the terms "relapse" and "recurrence" are actually synonymous, so it's been proposed we allow both terms.

- change the term "relapse" to "relapse or recurrence" in the `disease_status_at_followup` codelist.

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
