### ISSUE TITLE
Feature Request: Create codelist for staging groups and stage systems

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#122]
Will generate a codelist containing list of all possible stage groups.This codelist will be used in the following fields:
- clinical_stage_group
- pathological_stage_group
- recurrence_stage_group

Will update codelist used in `clinical_staging_system`, `pathological_staging_system` and `recurrence_staging_system` to make sure they contain all the staging systems recommended by AJCC.

Will also add a script validation check (similar to the one we use for tumour grading) to check the stage group value against the staging system specified.

Work in progress: https://docs.google.com/spreadsheets/d/1RCUqJ2DeK5vynGrYzhLOu-UAs9Kvxx_4L_5sWo_TtHc/edit?usp=sharing

**Comment by hknahal** [comment]
Related to https://github.com/icgc-argo/argo-dictionary/issues/122

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
