### ISSUE TITLE
🐛 treatment.age_at_consent_for_treatment has no units.  

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#124]
treatment.age_at_consent_for_treatment has no units. 

Should this be, `in year`s? 

![image](https://user-images.githubusercontent.com/15824252/81998870-8c4a7b00-9621-11ea-8132-fd9c51735efb.png)

**Comment by rosibaj** [comment]
@hknahal did we have units for this one?

**Comment by rosibaj** [comment]
im assuming is age it is years but want to confirm

**Comment by rosibaj** [comment]
@hknahal do we have units for this field?

**Comment by hknahal** [comment]
No longer required since this field has been removed (related to https://github.com/icgc-argo/argo-dictionary/issues/232 and PR https://github.com/icgc-argo/argo-dictionary/pull/243)
