### ISSUE TITLE
🐛 Script failing when t,n,m headers aren't even provided

### ISSUE THREAD

**Issue by wajiha-oicr** [icgc-argo/argo-dictionary#125]
## Describe the bug
- script was complaining about wrongly provided fields when the headers weren't defined, in the case of non ajcc values

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Submit a primary diagnosis file with clinical tumour staging system set to 'murphy'
2. Don't provide headers ( thus values) for t, n , m categories
3. Get an error stating you wrongly provided values for those categories

**Comment by rosibaj** [comment]
Tested with a FOLLOWUP file.

1. Uploaded `murphy` and INCLUDED TNM fiedsl.  Got the expected error

![image](https://user-images.githubusercontent.com/15824252/82398093-fe570180-9a1f-11ea-8633-81e440a70252.png)

2. Uploaded murphy, and removed fields values.  The file was correctly accepted
![image](https://user-images.githubusercontent.com/15824252/82398080-f72ff380-9a1f-11ea-8d7f-38ae9b074cdc.png)


3. Removed the headers:
- recurrence_t_category	
- recurrence_n_category	
- recurrence_m_category	
- recurrence_stage_group	
- posttherapy_tumour_staging_system

The file was correctly accepted 
![image](https://user-images.githubusercontent.com/15824252/82398267-6dccf100-9a20-11ea-8e8b-2c41f8c237f2.png)

**Comment by rosibaj** [comment]
@wajiha-oicr this lgtm from my tests  - @blabadi are you also able to upload your file now?
