### ISSUE TITLE
🐛 Drug Dosage units should be NUMBER not Integer

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#129]
I cannot submit decimals for drug dosages:
![image](https://user-images.githubusercontent.com/15824252/82068641-4254aa00-96a0-11ea-9924-987efeeb80c9.png)

# expected behaviour
these values should allow integers

# solution
change from type `integer` to `number`
dictionary locations
https://github.com/icgc-argo/argo-dictionary/blob/69f864d1ad1a570cc7c639bc0cfc178eb7373920/schemas/hormone_therapy.json#L92
https://github.com/icgc-argo/argo-dictionary/blob/69f864d1ad1a570cc7c639bc0cfc178eb7373920/schemas/chemotherapy.json#L81

**Comment by kcullion** [comment]
@rosibaj I was able to submit a decimal value in both the chemo and hormonal files. Will wait for your dictionary updates to test your data type change (from integer to number)
<img width="1267" alt="2020-05-25_1658" src="https://user-images.githubusercontent.com/18424138/82843069-fa0c6780-9ea9-11ea-9493-78ab28490c60.png">
<img width="1285" alt="2020-05-25_1703" src="https://user-images.githubusercontent.com/18424138/82843070-fbd62b00-9ea9-11ea-84f0-08a9357937b4.png">

**Comment by rosibaj** [comment]
verified on production
