### ISSUE TITLE
Feature Request: Add optional fields for clinical trial information

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#130]
Add two optional fields in Treatment table for clinical trial information

- clinical_trials_database: Will consist of a codelist which will contain (will add more if requested):
- "NCI Clinical Trials"
- "EU Clinical Trials Register"

- clinical_trial_number: This will contain a script validation that will use a regex to ensure the format of the clinical trial number matches that clinical_trial_database.

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-dictionary/pull/171

**Comment by rosibaj** [comment]
Tested in QA environment on dictionary 49.7 
- was able to upload a treatment file with no clinical db information
- was able to upload and see the script run and get the expected errors:
![image](https://user-images.githubusercontent.com/15824252/83583153-96211900-a511-11ea-842f-1ab107a3c8b5.png)
- when fixed got the correct upload and validation passed:
![image](https://user-images.githubusercontent.com/15824252/83583208-be107c80-a511-11ea-9892-87a45a316070.png)

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
