### ISSUE TITLE
Add note about comma with array

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-dictionary#134]
I think we should mention somewhere that data submitters can submit an array of values here and how to do so.

Something like:
<img width="1396" alt="2020-05-20_1601" src="https://user-images.githubusercontent.com/18424138/82492149-bbdf0480-9ab3-11ea-9ae2-3dc3e8542147.png">

**Comment by rosibaj** [comment]
@hknahal Do you the we should add an `Array` metadata tag that shows up somewhere?

**Comment by hknahal** [comment]
I agree, we should include this so data submitters know they can submit multiple values. @rosibaj Where can we add the `Array` metadata tag? Do you think we should replace `TEXT` with `Array` instead?

**Comment by kcullion** [comment]
@hknahal Will people know that the array means separate with a comma? sometimes it's semicolon...
Maybe there also needs to be a clear explanation on this page somewhere in case someone doesn't know what "array" means

**Comment by hknahal** [comment]
@kcullion Yes - that's a good point. I agree, I think not everyone will understand what an "array" is (maybe "list" would  be better?). I'll update the description to say to use commas if they want to include multiple terms.

**Comment by rosibaj** [comment]
@hknahal should this be in "Examples" instead? or Notes?  Description is about the content of what the field means?

**Comment by kcullion** [comment]
Yeah I think it should be in the notes...and with examples (see my screenshot)

**Comment by hknahal** [comment]
Agreed. I'll add this to the "Notes" section add examples as well.

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/83571364-9ca19780-a4f5-11ea-8cd4-03eb280e148a.png)

deployed dictionary 0.12
