### ISSUE TITLE
Feature Request: Add link to RxNorm web interface and API in description field for drug name fields

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#136]
Will add a link to RxNav (the RxNorm web interface) and their API in case data submitters need to lookup the RxNorm CUID:

RxNav: https://mor.nlm.nih.gov/RxNav/
RxNorm API: https://mor.nlm.nih.gov/download/rxnav/RxNormAPIs.html#

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-dictionary/pull/144

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
