### ISSUE TITLE
Feature Request Change treatment_type to accept array of treatments

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#143]
## Detailed Description
We currently have 3 terms in the`treatment_type` codelist for combination treatments. For example "Combined chemo+radiation therapy". It's possible projects use other combination treatments, so we can anticipate adding additional terms to this codelist, which will become difficult to manage. 

## Possible Implementation
- Remove the following "combined" treatment terms:
     - Combined chemo+immunotherapy
     - Combined chemo+radiation therapy
     - Combined chemo-radiotherapy and surgery

- Change treatment_type to accept an array of values instead of a single value from the codelist. So for example, if a patient had combined chemotherapy and radiation therapy treatment, the data submitter would submit an array of two treatments:

        `treatment_type: ["Chemotherapy", "Radiation therapy"]`

     - order does not matter (ie. `treatment_type: ["Chemotherapy", "Radiation therapy"]` and `treatment_type: ["Radiation therapy", "Chemotherapy"]` are the same.
    - values must be unique (ie. treatment_type: `["Chemotherapy", "Radiation therapy", "Chemotherapy"]` not allowed

**Comment by kcullion** [comment]
Also, add a note so that submitters know this is how you combine treatments

**Comment by jaserud** [comment]
@rosibaj Clinical 1.30.0 release is now checking treatment_type as an array during validation. I updated dictionary in QA to 51.3 with the proposed changes in the PR https://github.com/icgc-argo/argo-dictionary/pull/189.
