### ISSUE TITLE
Dictionary feedback

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-dictionary#145]
- [x] For Program ID notes: `This is the unique id that is assigned to your program.  If you have logged into the platform, this is the Program Id that you see in the Submiission area.`
Submission is spelt wrong - but I would also change this to 
If you have logged in to the Platform, this is the Program Id that you see in the Program Services area. For example, PACA-CA is a Program ID. 

- [x] Sample Registration file description. 
`The collection of elements required to register the required Donor-Specimen-Sample data to the ARGO Platform. Registration of samples is required before genomic and clinical data submission can proceed.`
**For consistency with the terms we are using, change to:**
`The collection of elements required to register the required Donor-Specimen-Sample data to the ARGO Data Platform. Registration of samples is required before molecular and clinical data submission can proceed.`

- [x] Donor file description
The collection of data elements related to a specific donor in a specific ICGC-ARGO program.
**change to:**
The collection of data elements related to a specific donor in an ARGO program.
(we don't use a dash ever, and in the program-id desc we say ARGO program)

- [x] In Primary diagnosis ID - do we want to say this is collected because a donor can have more than one PD? Or put that in the docs somewhere so they know they can submit more than one (as the word "primary" seems like only one is allowed"
Or perhaps add in PD file description, like you did for the supplimental treatment files (note to add more than one drug)

`The collection of data elements related to a donor's primary diagnosis. The primary diagnosis is the first diagnosed case of cancer in a donor. To submit multiple primary diagnoses for a single donor, please submit multiple rows in the primary diagnosis file for this donor.`
This will depend on what's decided for: https://github.com/icgc-argo/argo-clinical/issues/435#issuecomment-632760443

NOTE RB: this ticket is actually not related to multiple PD rows ; multiple allowed either way,

- [x] for treatment_type note, I think we can be more specific so they don't just have to wait to see an error. Also there's a type on treatment
`Depending on the treatment_type selected, additional treatment details may be required to be submitted. If the treatment_type includes Chemotherapy, Radiation or Hormonal therapy, please submit the supplemental file core fields. `
- [ ]  ~Also, treatment_type permissible values are not in alpha order.~

- [x] treatment_start_interval - add a period at the end of the note
- [x] treatment_duration - add a period at the end of the description

- [x] For Chemotherapy and Hormone Therapy file descriptions 
`For multiple treatment agents in a single regimen, submit multiple rows in the chemotherapy file.`
- I think we should use the word "drug" instead of "agent". As that's what the field labels are using. I think this can also be reworded to:
`To submit multiple treatment drugs for a single regimen, please submit multiple rows in the chemotherapy file.`

- [x] Follow-up file description, to make consistent with others, can say
`The collection of data elements related to a specific follow-up visit to a donor. A follow-up is defined as any point of contact with a patient after primary diagnosis. To submit multiple follow-ups for a single donor, please submit multiple rows in the follow-up file for this donor.`

- [ ] ~for follow-up, should the ids all be at the top of the list? are submitter_primary_diagnosis_id
 and submitter_treatment_id not required for a followup?~ 
RB No these are not required; they are optional on a followup visit

- [ ] the notes should consistently be 
`This field is required to be submitted if disease_status_at_followup indicates a progression or relapse value.`
for: relapse_type, method_of_progression_status, anatomic_site_progression_or_recurrences, recurrence_tumour_staging_system

- [x] For posttherapy_stage_group, can the note be worded like the other ones and provide more info? Like:
`This field is required only if the selected posttherapy_tumour_staging_system is...`

**Comment by rosibaj** [comment]
> for treatment_type note, I think we can be more specific so they don't just have to wait to see an error. Also there's a type on treatment
Depending on the treatment_type selected, additional treatment details may be required to be submitted. If the treatment_type includes Chemotherapy, Radiation or Hormonal therapy, please submit the supplemental file core fields.

Regarding this one, this message is too specific and will quickly become outdated.  I updated to a more informative but generic message. 

> Also, treatment_type permissible values are not in alpha order.

already a  ticket for this #99 

> - [ ] the notes should consistently be 
`This field is required to be submitted if disease_status_at_followup indicates a progression or relapse value.`
for: relapse_type, method_of_progression_status, anatomic_site_progression_or_recurrences, recurrence_tumour_staging_system

Ther e are changes already in this area #131 .  Will not adress here until those are completed.

**Comment by kcullion** [comment]
@rosibaj I noticed Bashar's comment on this: https://github.com/icgc-argo/argo-clinical/issues/435#issuecomment-634043433

We should probably add this as a note

**Comment by rosibaj** [comment]
@kcullion we should make a different ticket for that. we are releasing the dictionary today.

**Comment by rosibaj** [comment]
actually it already exists #143

**Comment by kcullion** [comment]
That ticket doesn't really say anything about updating the notes in the dictionary. Does it just come along with that change?

**Comment by rosibaj** [comment]
make a comment there. updating the treatment_types is a large feature and its not in scope of these small changes.  It requires some code updates and deeper testing, so we cannot bundle it with these changes here.  Right now, adding that to the dictionary would be incorrect and would instruct users of the wrong things since they are not actually alllowed to do that.

**Comment by kcullion** [comment]
yes I added a comment to that ticket @rosibaj
