### ISSUE TITLE
🐛 Missing tumour_grading_system should invalidate

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#151]
## Describe the bug
The `tumour_grading_system` field is a required field, but the validation passes even if the `tumour_grading_system` field is empty. It also fails if both the `tumour_grading_system` and `tumour_grade` fields are both empty:

(using dictionary version 47.2)

![missing_tumour_grading_system](https://user-images.githubusercontent.com/4992044/82949591-e3c9de80-9f71-11ea-8d05-069a9dfa5a45.png)

## Expected behaviour:
The validation should fail if `tumour_grading_system` is empty.
It should also fail if both `tumour_grading_system` and `tumour_grade` are empty.

**Comment by hknahal** [comment]
After discussing with Bashar, the tumour/normal check is actually done when the data submitter hits the `Validate` button. The behaviour shown in the screenshot here is actually normal and the user will see an error message after the validate.

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
