### ISSUE TITLE
🐛 Tumour grading should not be submitted for normal specimens

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#152]
## Describe the bug
Tumour grading should only be required if the specimen is of tumour type. When a value is submitted for the `tumour_grading_system` and `tumour_grade` fields when the submitter_specimen_id is of "normal" type, the validation passes incorrectly:

In this case, the submitter_specimen_id `test-sample-10` is a normal specimen.
Dictionary version tested: 47.2

![tumour_grading_for_normal_specimen](https://user-images.githubusercontent.com/4992044/82950709-cac22d00-9f73-11ea-8f37-9afd7287731e.png)

## Expected behaviour
If the specimen in `submitter_specimen_id` is a normal specimen and a value is submitted in the `tumour_grading_system` and `tumour_grade` fields, then validation should fail and report an error saying tumour grading should only be submitted for tumour specimens.

**Comment by hknahal** [comment]
Found during testing that this looks like it's been fixed, so it's no longer an issue:

![152_fixed](https://user-images.githubusercontent.com/4992044/83457111-f8edb400-a42e-11ea-8b70-9dc344b57d31.png)

**Comment by hknahal** [comment]
After discussing with Bashar, the tumour/normal check is actually done when the data submitter hits the Validate button. The behaviour shown in the screenshot (tumour grade submitted for normal specimen) here is actually normal and the user will see an error message _**after**_ the validate.

**Comment by rosibaj** [comment]
Tested on dictionary 49.7 on QA env
- can correctly upload specimen file and not get errors
- can see on validate that the correct tumour/normal validations are completed
