### ISSUE TITLE
Feature Request : Update dictionary notes to mention using a pipe delimiter instead of comma for fields that accept multiple terms

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#155]
We previously mentioned in the "notes" section to use a comma to submit multiple values for a field. Will need to update this say to use a pipe (`|`) delimiter instead.

**Comment by kcullion** [comment]
@rosibaj @hknahal 
like we did for tacking on the reg-expression for the ids, can we add this instructions for pipe delimitated values to the error message too?
<img width="1193" alt="Screen Shot 2020-06-01 at 11 48 37 AM" src="https://user-images.githubusercontent.com/18424138/83427097-2e2dde00-a3fe-11ea-92a1-b9932372d9b5.png">

**Comment by rosibaj** [comment]
@kcullion this is more a question for bashar/jaser, not the dictionary.

**Comment by kcullion** [comment]
@rosibaj I asked @jaserud and he said they can't tell what the submitter did wrong, but yeah could maybe do a more general message like
"This value is no permissible for this field. If you are trying to submit multiple values, please separate them with a | character."

But I'll leave up to you if you think it's necessary.

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-clinical/issues/541 @kcullion for future consideration!!
