### ISSUE TITLE
🐛 Remove validation check for empty tumour_grade and tumour_grading_system

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#166]
## Describe the bug

The following code (click [here](https://github.com/icgc-argo/argo-dictionary/pull/161/files#diff-17efe73b83c0f6ed74aacae168f3411eR94-R104)) was added to take care of https://github.com/icgc-argo/argo-dictionary/issues/151:

![82949591-e3c9de80-9f71-11ea-8d05-069a9dfa5a45](https://user-images.githubusercontent.com/4992044/83557561-dd8eb180-a4df-11ea-8b8a-3216ba175d4f.png)

It was assumed the tumour/normal check was done at the `Upload` step, but as Bashar explained, it's actually done when the data submitter hits the `Validate` button. So the above screenshot at the `Upload` step is normal, and the user won't see the error until they try validating. As a result, the current validation check is applied to all data, regardless of whether it's a normal or tumour specimen. This is causing the bug reported in https://github.com/icgc-argo/argo-dictionary/issues/165. 

## To resolve:
Remove the previously added validation checks: https://github.com/icgc-argo/argo-dictionary/pull/161/files

**Comment by rosibaj** [comment]
@hknahal the change for this lgtm! 

I tried it in dictionary 49.3, and do not see the unexpected errors on qa anymore
