### ISSUE TITLE
🐛 Missing a few stage groups in codelist for non-AJCC staging systems

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#168]
## Describe the bug
Codelist for stage group is missing a few stages from the non-AJCC staging systems.

![stage_group_bug](https://user-images.githubusercontent.com/4992044/83568973-cfe22780-a4f1-11ea-9654-4ef96a270ed7.png)

Will update codelist to include all non-AJCC stage groups as well.

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
