### ISSUE TITLE
Feature Request : A few minor updates

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#178]
## Detailed Description

Donor table:
- `laterality_of_prior_malignancy` -> currently this is the only free-text field. Would prefer to have standard terminology here. Will add codelist derived from NCI: https://cdebrowser.nci.nih.gov/cdebrowserClient/cdeBrowser.html#/valueDomain?conceptInput=C25185
- add `unknown` to `cause_of_death`. This was based on feedback from projects.

Treatment table:
1. remove Remove Monoclonal antibodies (for liquid tumours). This is #1 from https://github.com/icgc-argo/argo-dictionary/issues/110.

**Comment by rosibaj** [comment]
Tested in dictionary 50.1 in QA environment 
-  I am no longer allowed to submit free text; get the expected error
![image](https://user-images.githubusercontent.com/15824252/83710589-24b79800-a5ef-11ea-850a-1b0c61e45415.png)

- when i have all the codelists values, validation passes

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
