### ISSUE TITLE
Feature Request: Optional treatment fields

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#184]
data submitters are already asking about these. Added optional treatment fields:

line_of_treatment
days_per_cycle
number_of_cycles
outcome_of_treatment
toxicity_type
hemotological_toxicity
adverse_events

**Comment by rosibaj** [comment]
@hknahal should `adverse_events` be an array?
![image](https://user-images.githubusercontent.com/15824252/83711143-6268f080-a5f0-11ea-9c9b-2dcdff116998.png)

**Comment by rosibaj** [comment]
Other than the above question, tested on dictionary 50.1 on QA environment 
- codes lists working well
- optinoal fields are indeed optionally submittable

**Comment by hknahal** [comment]
> @hknahal should `adverse_events` be an array?
> ![image](https://user-images.githubusercontent.com/15824252/83711143-6268f080-a5f0-11ea-9c9b-2dcdff116998.png)

@rosibaj Yes, it should be. I'll correct it.

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
