### ISSUE TITLE
Feature Request : Split "therapeutic_intent" field into 2 separate fields

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#199]
According to CDISC (Clinical Data Interchange Standards Consortium), in the context of clinical trials, treatment can be categorized according to **intent** and **setting**. A treatment’s intent (NCI Thesaurus Code:  [C124307](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C124307)) is the best kind of effect it could be expected to have on the disease. A treatment setting (NCI Thesaurus Code:  [C124277](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C124277)) describes the purpose of the treatment.  mCODE uses a similar controlled terminology for "[Treatment Intent](http://hl7.org/fhir/us/mcode/ValueSet-mcode-treatment-intent-vs.html)". The current controlled vocabulary for the ARGO `therapeutic_intent` field contains terms from both concepts, so in keeping in line with clinical standards and ARGO's model of using one field per concept, the current `therapeutic_intent` field will be split into 2 separate fields.

Current `therapeutic_intent` field:
- Adjuvant
- Concurrent
- Curative
- Neoadjuvant
- Not applicable
- Palliative
- Unknown

**New fields:**

1. `treatment_intent`
    - Curative
    - Palliative
    - Unknown

2. `treatment_setting`
    - Neoadjuvant 
    - Adjuvant 
    - Advanced/Metastatic
    - Not applicable

The term "Concurrent" (which means a treatment that is given at the same time as another), will be removed since we already allow multiple treatment types to be submitted in the `treatment_type` field for combination treatments.

**Comment by blabadi** [comment]
this ticket requires clinical data migration to be coordinated before dictionary migration happen to avoid invalidation for the renaming portion of fields
