### ISSUE TITLE
Feature Request: Add new term "Progression - NOS" to disease_status_at_followup field

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#200]
## Description

The current `disease_status_at_followup` field consists has the following controlled terminology:
- Complete remission
- **Distant progression**
- **Loco-regional progression**
- No evidence of disease
- Partial remission
- Relapse or recurrence
- Stable

During a recent meeting with the TFRI Data Management Working Group (for MOH), some clinicians explained that in settings outside of clinical trials or when clinical data is coming from retrospective studies, it is difficult to discern whether the disease status is distant progression or loco-regional progression. But these terms are commonly used in clinical trials so we want to keep these terms in the controlled vocabulary. 

## Implementation

To strike a balance between the two, Lincoln suggested a new term "Progression, NOS” be added to the controlled terminology (NOS means "not otherwise specified")

**Comment by rosibaj** [comment]
confirmed on dictionary deploy - visible on 1.1 of data dictionary on site
