### ISSUE TITLE
Feature Request : Refine definition for "age_at_diagnosis" to indicate what the diagnosis should be based on.

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#201]
## Description

During discussions with the TFRI Data Management working group (for MOH), a question came up about the ARGO `age_at_diagnosis` field and whether diagnosis should be based on the _earliest_ diagnosis (the first time the clinician concluded the patient had cancer) or _definitive_ diagnosis (ie. based on biopsy). It's usually based on the first tissue-based pathological diagnosis, but there are cases where the diagnosis is based on just imaging (this would be the earliest diagnosis). The time between the earliest diagnosis and definitive diagnosis could be a matter of a few years, so it's important to define what this field should be based on. Here's an example:

- Patient had imaging done in 2020. Diagnosed with cancer based on imaging -> this the earliest diagnosis. Because the disease is metastatic, didn’t want to do biopsy, so don’t have tissue-based pathological information about the cancer.
- 3 years go by. A biopsy is done. Able to do histology of metastases to get staging information -> this is the definitive diagnosis.

Lincoln suggested that the `age_at_diagnosis` field should be based on the earliest diagnosis, since this is when the patient knows they have cancer and they may start treatment before they have a definitive diagnosis.

## Implementation
Will update description for `age_at_diagnosis` field to indicate that it should be based on the earliest diagnosis.

**Comment by rosibaj** [comment]
confirmed on dictionary deploy - visible on 1.1 of data dictionary on site
