### ISSUE TITLE
Refactor scripts to return a function and take input object instead of global variables

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-dictionary#202]
To run scripts faster we need to make them return functions instead of relying on global variables for their input

**Comment by rosibaj** [comment]
@blabadi Does this have a dependency with a version of clinical?

**Comment by blabadi** [comment]
> @blabadi Does this have a dependency with a version of clinical?

yes they have to go together

**Comment by rosibaj** [comment]
@blabadi do we know the version yet?

**Comment by blabadi** [comment]
> @blabadi do we know the version yet?

no not yet, still in coding there

**Comment by blabadi** [comment]
The release candidate for this is here https://github.com/icgc-argo/argo-clinical/pull/574

**Comment by rosibaj** [comment]
Have not notices any issues with this at all in uploads he past few days
