### ISSUE TITLE
Feature Request : Make either clinical or pathological stage classification fields required, the other optional

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#209]
This ticket proposes making _**either**_ the clinical stage classification fields  (`clinical_t_category`, `clinical_n_category`, `clinical_m_category`, `clinical_stage_group`, `clinical_tumour_staging_system`) or pathological stage classification fields (`pathological_t_category`, `pathological_n_category`, `pathological_m_category`, `pathololgical_stage_group`, `pathological_staging_system`) required because for certain cancer types or situations, it is not always possible to get both the clinical and pathological stage classifications.

## Detailed Description

Definitions of clinical and pathological stage classification according to AJCC:

`"Clinical stage classification is based on patient history, physical examination, and any imaging done before initiation of treatment. Imaging study information may be used for clinical staging, but clinical stage may be assigned based on whatever information is available. No specific imaging is required to assign a clinical stage for any cancer site. When performed within this framework, biopsy information on regional lymph nodes and/or other sites of metastatic disease may be included in the clinical classification."`

`"Pathological stage classification is based on clinical stage information supplemented/modified by operative findings and pathological evaluation of the resected specimens. This classification is applicable when surgery is performed before initiation of adjuvant radiation or systemic therapy."`

During discussions with both the MOHCC and ARGO clinical working groups, it was brought up that there are certain cancer types or situations where it is not possible get both the clinical and pathological stage classifications. An example is advanced brain cancer or pediatric retinoblastoma where biopsy is too risky, so pathological stage classification cannot be done. In the case of brain cancer, imaging may be done to diagnose the cancer so only clinical staging classification can be done. In the case of pediatric retinoblastoma, a non-invasive diagnostic test called electroretinogram is used to get clinical stage classification about the tumour. In both these cases, the clinical submission validation will fail because the pathological stage classification fields cannot be filled in. In some other cancers such as advanced/metastatic pancreatic cancer, certain diagnostic tests such as imaging may not provide enough information to document the `clinical_n_category` or `clinical_m_category` fields, and surgery is done instead to get the pathological stage classification. In this case, the validation will fail because the clinical stage classification fields cannot be filled in.

## Possible Implementation

We can allow **_either_** set of fields to be required. So if the clinical stage classification fields are submitted, the pathological stage classification fields become optional and we can still validate the submission. Likewise, if the pathological stage classification fields are submitted, the clinical stage classification fields become optional and we can still validate the submission. If both sets of fields are missing, then the validation will fail because at least one set of fields is required.

|File Scheama| Field Name | Scenario 1| Scenario 2 | Scenario 3 |Scenario 4 |
|------------|------------ | -----------|------------ | -----------| -----------|
|primary_diagnosis| `clinical_t_category` | submitted | missing | missing |submitted |
|primary_diagnosis| `clinical_n_category` | submitted | missing | missing |submitted |
|primary_diagnosis| `clinical_m_category` | submitted | missing | missing |submitted |
|primary_diagnosis| `clinical_stage_group` | submitted | missing | missing |submitted |
|primary_diagnosis| `clinical_tumour_staging_system` | submitted | missing | missing |submitted |
|specimen| `pathological_t_category` | missing | submitted | missing |submitted |
|specimen| `pathological_n_category` | missing | submitted | missing | submitted |
|specimen|  `pathological_m_category` | missing | submitted | missing | submitted |
|specimen| `pathological_stage_group` | missing | submitted | missing | submitted |
|specimen| `pathological_staging_system` | missing | submitted | missing |submitted  |
||Validation: | can validate | can validate | will be invalid | can validate |

- Since these fields are in different files, this would need to be a cross-file validation done in clinical. Scripts don't have the context of additional files or the database values.
- In the case that either specimen/primary_diagnosis are uploaded alone with t/n/m values populated, they should validate (adding data is always accepted in this case)
- In the case that either specimen or primary_diagnosis file is uploaded without ant t/n/m values populated, then the validation would need to check if the other values were populated, either already in the db or submitted together with the other file. The error message could say:
```
TNM staging is required for either clinical or pathological staging.  
Please submit both a `primary_diagnosis` record and a `specimen`
 record together for validation with at least one of these populated.
```

## Scope of this Ticket
- [ ] Update the `cross-file` validations to allow for the ^ above set of rules to be followed. 
- [ ] Update the data-dictionary `meta` fields to reflect the clinical dependency. 
- [ ] Update the wiki to reflect the new Validation rule: https://wiki.oicr.on.ca/display/icgcargotech/Clinical+Submission+Validation+Errors

**Comment by rosibaj** [comment]
@hknahal I have added a file column to your table to be more clear: 

- Since these fields are in different files, this would need to be a `cross-file` validation done in clinical.  Scripts don't have the context of additional files or the database values. 
- Since this involves many settings, i think it creates a dependency between files that would require them to be uploaded together (like `treatment_type` and `treatment_type` 

For example: 
- In the case that either specimen/primary_diagnosis are uploaded alone with t/n/m values populated, they should validate (adding data is always accepted in this case)
- In the case that either `specimen` or `primary_diagnosis` file is uploaded without ant t/n/m values populated, then the validation would need to check if the other values were populated, either already in the db or submitted together with the other file. The error message could say:

```
TNM staging is required for either clinical or pathological staging.  Please submit both a `primary_diagnosis` record and a `specimen` record together for validation with at least one of these populated.
``

@hknahal is this an acceptable experience for users? 
@blabadi is this possible?

**Comment by hknahal** [comment]
@rosibaj Yes, this would work for users.

**Comment by rosibaj** [comment]
Testing files: 
 
Both populated, both submitted at same time:
[donor.txt](https://github.com/icgc-argo/argo-dictionary/files/5968616/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-dictionary/files/5968617/primary_diagnosis.txt)
[specimen.txt](https://github.com/icgc-argo/argo-dictionary/files/5968618/specimen.txt)

**Result**: I was able to successfully upload both files, and cross-file validation passed. 

Only `Specimen`  populated, both files submitted::
[donor.txt](https://github.com/icgc-argo/argo-dictionary/files/5968659/donor.txt)
[primary_diagnosis.txt](https://github.com/icgc-argo/argo-dictionary/files/5968660/primary_diagnosis.txt)
[specimen.txt](https://github.com/icgc-argo/argo-dictionary/files/5968661/specimen.txt)

**Result**: I was able to successfully upload both files, and cross-file validation passed. 

Only `Specimen` populated, specimen submitted first:
- i uploaded donor + pd first.  that validated successfully. the pd did not have values. 
- i registered both of these successfully
- i uploaded `specimen` with values. it worked and validated. 

Neither:
**Result**: I got a validation error and had to fill one set of fields in.

**Comment by rosibaj** [comment]
Deployed to prod - followup issue https://github.com/icgc-argo/argo-clinical/issues/641 created for the following sprint.
