### ISSUE TITLE
Make 4 fields non-core

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#214]
- 4 percentages 
-

**Comment by hknahal** [comment]
Confirmed with WG leader that we can make the following four fields optional:
- percent_proliferating_cells
- percent_inflammatory_tissue
- percent_stromal_cells
- percent_necrosis

`percent_tumour_cells` must stay mandatory.

**Comment by rosibaj** [comment]
When the dictionary is published, verify language in docs site is communicate correctlt regarding these fields.
