### ISSUE TITLE
Feature Request: Submit each comorbidity as new entry instead of list of values in one field

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#220]
This issue is related to the Extended (Optional) [Comorbidity](https://docs.google.com/spreadsheets/d/1XsftOlg-ZEDNlEiHe_IYaUykD2LQaza-WT3YARUTXD0/edit?usp=sharing) clinical table which has not yet been implemented (currently being reviewed by TCA Working Group)

### Issue:
A patient can have more than one comorbidity, so we can expect a list of comorbidities in the `comorbidity` field. Similarly, each comorbidity would have its own `age_at_comorbidity_diagnosis`. This would mean we would need to accept a list of values where order matters (since comorbidity and age values need to correspond) and values don't need to be unique (for example, a patient could have been diagnosed with two comorbidities at the same age (example: `comorbidity`: `[E10, K85]` and `age_of_comorbidity_diagnosis`: `[32, 32]`). This is similar to the issue described in https://github.com/icgc-argo/argo-dictionary/issues/153. 

### Possible Implementation:
Instead of accepting a list of values and determining how to ensure the order of the non-unique values, we can require each comorbidity to be submitted as a new entry (on a new line). See [**here**](https://docs.google.com/spreadsheets/d/13bs-DiTKLEgDvAcl1t9zmJ_Q0kOkMdTSTfOQ-Uu2kDQ/edit?usp=sharing) for example submission of comorbidity data. We can also amalgamate/move some of the optional fields in the `Donor` table since they can be covered in the `Comorbidity` table. This would eliminate the need to resolve https://github.com/icgc-argo/argo-dictionary/issues/153 and would require the following changes:
- Move `prior_malignancy` field from `Donor` table to `Comorbidity` table since a prior cancer malignancy is a comorbidity.
- Remove `cancer_type_prior_malignancy` field from `Donor` table since the `comorbidity` field in the `Comorbidity` table covers this (if `prior_malignancy` is `Yes`, then the ICD-10 code of the prior cancer would be entered in the `comorbidity` field).
- Remove `age_at_prior_malignancy` from `Donor` table since `age_at_comorbidity_diagnosis` in `Comorbidity` table would cover this.
- a genetic disorder (`genetic_disorder` field in `Comorbidity` table) would not require `age_at_comorbidity_diagnosis` since the patient would have been born with the genetic disorder (unlike diabetes which can start later in life for example).
- In the case of multiple comorbidities, we would require the data submitter to submit each comorbidity as a new entry. Fields that are not applicable would be left blank.

**Comment by rosibaj** [comment]
@rosibaj 
- confirm validation rules; does this make any changes within?
- run a test migration with the new dictionary in dev and see how it goes first

**Comment by rosibaj** [comment]
Removed: 
```
    {
      "description": "Prior malignancy affecting donor.",
      "name": "prior_malignancy",
      "restrictions": {
        "codeList": "#/list/yes_no"
      },
      "valueType": "string",
      "meta": {
        "displayName": "Prior Malignancy",
        "examples": "C41.1, C16.9, C00.5, D46.9"
      }
    },
    {
      "description": "The code to represent the cancer type of a prior malignancy using the WHO ICD-10 code (https://icd.who.int/browse10/2019/en) classification.",
      "name": "cancer_type_prior_malignancy",
      "restrictions": {
        "regex": "^[C|D][0-9]{2}(.[0-9]{1,3}[A-Z]{0,1})?$"
      },
      "valueType": "string",
      "meta": {
        "displayName": "Cancer Type Prior Malignancy"
      }
    },
    {
      "description": "If donor has history of prior malignancy, indicate age at previous diagnosis, in years.",
      "name": "age_at_prior_malignancy",
      "valueType": "integer",
      "meta": {
        "displayName": "Age at Prior Malignancy"
      }
    },
    {
      "description": "If donor has history of prior malignancy, indicate laterality of previous diagnosis. (Codelist reference: NCI CDE: 4122391)",
      "name": "laterality_of_prior_malignancy",
      "valueType": "string",
      "restrictions": {
        "codeList": ["Bilateral", "Left", "Midline", "Not applicable", "Right", "Unilateral", "Unilateral, side not specified", "Unknown"]
      },
      "meta": {
        "displayName": "Laterality at Prior Malignancy"
      }
    },
```

**Comment by rosibaj** [comment]
Deployed dictionary version 1.7: https://docs.icgc-argo.org/dictionary
