### ISSUE TITLE
Feature Request: Reorder clinical staging fields so they are consistent with pathological staging fields

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#228]
Reorder clinical staging fields so they are consistent with pathological staging fields.

**Current order in Primary Diagnosis:**

clinical_tumour_staging_system
clinical_stage_group
clinical_t_category
clinical_n_category
clinical_m_category

**Re-order**
clinical_tumour_staging_system
clinical_t_category
clinical_n_category
clinical_m_category
clinical_stage_group

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-dictionary/pull/233

**Comment by rosibaj** [comment]
Deployed dictionary version 1.7: https://docs.icgc-argo.org/dictionary
