### ISSUE TITLE
Update script validation for [clinical|pathological]_stage_group fields to include requirement for tumour staging fields

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#229]
Update script validation for `clinical_stage_group` field to make the `clinical_tumour_staging_system` required if `clinical_stage_group` field is submitted.
Do the same for `pathological_stage_group` (ie. `pathological_tumour_staging_system` field should be required if `pathological_stage_group` field is submitted)

**Comment by hknahal** [comment]
https://github.com/icgc-argo/argo-dictionary/pull/233
https://github.com/icgc-argo/argo-dictionary/pull/236

**Comment by rosibaj** [comment]
Deployed dictionary version 1.7: https://docs.icgc-argo.org/dictionary
