### ISSUE TITLE
Add New Schema: Comorbidity

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#248]

**Comment by hknahal** [comment]
Comorbidity table: https://docs.google.com/spreadsheets/d/1w3X42_ffE32EVBqjjAxDqT47TX8-vFUwL1-DRHphwCc/edit#gid=1723897046

**Comment by rosibaj** [comment]
Tested in dictionary 100.2 on QA Environment: 

- [ ] Issue #1:

**Comment by hknahal** [comment]
Thanks @rosibaj I addressed the issues you reported and updated the script validations. 
I tested the updates in QA using dictionary version `102.1` using this example file: [comorbidity.txt](https://github.com/icgc-argo/argo-dictionary/files/6511789/comorbidity.txt)

The following checks are done:

1. (Row 2) prior_malignancy = "Yes" but ICD-10 code submitted in cormorbidity_type_code is not for cancer.
--> Error message: "If the 'prior_malignancy' field is submitted as 'Yes', then an ICD-10 code for cancer is expected in the 'comorbidity_type_code' field."

2. (Row 3) prior_malignancy is "no" or "unknown" or not submitted, and comorbidity_type_code is an ICD-10 code related to cancer.
--> Error message: "If an ICD-10 code for cancer is submitted in the 'comorbidity_type_code' field, then 'prior_malignancy' should be submitted as 'Yes'."

3. (Row 4 and 5) If 'laterality_of_prior_malignancy" is submitted, and 'prior_malignancy' is 'no', 'unknown' or missing:
--> Error message: "The 'prior_malignancy' field should be submitted as 'Yes' if the 'laterality_of_prior_malignancy' field is submitted."

4. (Row 6) If 'age_at_comorbidity_diagnosis' is submitted but 'comorbidity_type_code' field is missing:
--> Error message: "The 'comorbidity_type_code' field is required if '${$name}' is submitted."

5. (Row 7 and 8) If 'comorbidity_treatment' is submitted, but 'comorbidity_treatment_status' is 'no', 'unknown' or missing:
--> Error messsage: "The 'comorbidity_treatment_status' field should be submitted as 'Yes' if 'comorbidity_treatment' field is submitted."

6. (Row 9) All fields except submitter_donor_id are missing.
--> Error message: "comorbidity_type_code is a required field."

**Comment by rosibaj** [comment]
@hknahal I tested all of the above - they all look to be functioning correctly, with one "exception".  for `4.` this can never be triggered; `comorbidity_type_code` is a required field (described in `9.`, so if i dont submit `comorbidity_type_code` but do submit `age_at_comorbidity_diagnosis` then the message i get is `"comorbidity_type_code is a required field."`

Do we need to include `4.` based on the above comment ^^?

**Comment by hknahal** [comment]
@rosibaj Yes, you're right `.4` can't be triggered. I remember seeing this too and forgot to remove it from the list of checks. We don't need `.4`.
