### ISSUE TITLE
Add validation script that does not require treatment core fields if treatment_type is 'No treatment'

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#255]
## Description

If a patient had no treatment (ie. `treatment_type` = `No treatment`), then the following core fields should not be required since they do not apply:

- is_primary_treatment
- treatment_start_interval
- treatment_duration
- treatment_intent
- treatment_setting
- response_to_treatment

Example from MUTO-INTL `Treatment` clinical data submission:

![treatment_submission](https://user-images.githubusercontent.com/4992044/111512603-4c16c600-8726-11eb-8730-37f651d9bc44.png)

## Possible Implementation
- Add a validation script to perform this check (core fields are not required if `treatment_type` is `No treatment`)
- Also check optional fields when `treatment_type` is `No treatment` (it doesn't make sense to submit the optional field `days_per_cycle` if no treatment was given). 
- Ensure fields that accept integers are greater than 0 (should not accept negative values).

**Comment by rosibaj** [comment]
@hknahal i completed testing of you PR with dictionary 84.0 - all looks good to me here i could not find any bugs with this!

**Comment by rosibaj** [comment]
Included in Dictionary 1.8; migration confirmed on prod release.
