### ISSUE TITLE
Add lymph_nodes_examined_status field

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#256]
Since "number_lymph_nodes_positive" is a required field, a data submitter cannot leave it empty in cases where lymph nodes were not examined (use cases described below). More context is needed to correctly interpret the submitted values for "number_lymph_nodes_examined" and "number_lymph_nodes_positive".

|Field| Data Tier| Description| Accepted Value|
|----|-----|----|----|
|number_lymph_nodes_examined | Optional |The total number of lymph nodes tested for the presence of cancer | integer |
|number_lymph_nodes_positive | Required |The number of regional lymph nodes reported as being positive for tumour  metastases | integer |

Use Cases where this works:

- **Use Case 1:** Out of 30 lymph nodes examined for presence of cancer, 14 lymph nodes are positive for metastases
"number_lymph_nodes_examined": 30
"number_lymph_nodes_positive": 14

- **Use Case 2:** 16 lymph nodes were examined for presence of cancer but none had metastases.
"number_lymph_nodes_examined":  16
"number_lymph_nodes_positive": 0

- **Use Case 3:** Lymph nodes were examined for presence of cancer, but the number is unknown. There were no lymph nodes that tested positive for metastases out of the total unknown number examined.
"number_lymph_nodes_examined":  <blank>
"number_lymph_nodes_positive": 0<br/>
This would be interpreted as  "0 out of X lymph nodes examined were positive (where X is unknown but is a value greater than 0)". 

The following two use cases highlight how when "number_lymph_nodes_examined" is left blank, a value of zero for "number_lymph_nodes_positive" could be misinterpreted as meaning `an unknown number of lymph nodes were tested, and none were found to be positive for cancer`:

- **Use Case 4**: No lymph nodes were tested for presence of cancer because the patient was too old/frail to do surgery on to resect lymph nodes. Therefore it wasn't possible to determine how many lymph nodes were positive for metastases.
"number_lymph_nodes_examined":  <blank>
"number_lymph_nodes_positive": 0 <br/>
Ideally it would be better if "number_lymph_nodes_positive" were left blank because a zero can be interpreted as "no lymph nodes were found to be positive out of X number of lymph nodes examined (where X is unknown but is a value greater than 0)". A zero can be misinterpreted as Use Case 3.

- **Use Case 5**: No lymph nodes were tested for presence of cancer because there were no lymph nodes found in the resected specimen. As a result, it's not possible to know if there are any lymph nodes that could be positive for metastases.
"number_lymph_nodes_examined":  <blank>
"number_lymph_nodes_positive": 0 <br/>
Entering 0 for "number_lymph_nodes_positive" wrongly implies that none of the possibly unknown number of lymph nodes examined were positive, when actually no lymph nodes were examined to begin with. This could also be misinterpreted as Use Case 3.

## Possible Implementation
Add a new required field "lymph_nodes_examined_status" with the following controlled vocabulary:

|Accepted Value| Example |
|---|---|
|Yes| Use Cases 1 and 2 and 3 above |
|No| Lymph nodes were not tested for cancer (for example, patient refused) |
|Not applicable |Testing lymph nodes for cancer does not apply to certain cancers such as gestational trophoblastic tumours because the cancer rarely spreads there. There is not N category when staging using AJCC for gestational trophoblastic tumours.  |
|No lymph nodes found in resected specimen| Surgery was done but there were no lymph nodes found in the resected specimen.|
|Cannot be determined |Lymph nodes could not tested because they were removed previously, or couldn't be removed for testing  because patient was too frail or obese| 

The term "Unknown" is not included in this list because "number_of_lymph_nodes_positive" is a "Core" field (cannot leave this empty unless valid reason to do so).

The "number_lymph_nodes_positive" field will be allowed to be empty depending on the value submitted in the "lymph_nodes_examined_status" field. The "number_lymph_nodes_examined" would stay optional but if a value is submitted, it would be dependent on what was submitted in the "lymph_nodes_examined_status" field as well. This implementation would provide some context for the "number_lymph_nodes_examined" and "number_lymph_nodes_positive" field:

|lymph_nodes_examined_status|number_lymph_nodes_examined|number_lymph_nodes_positive|
|----|-----|-----|
|Yes|Optional <br/>If left blank, then means unknown/missing <br/> If number is submitted, it must be greater than 0|Required<br> If number_lymph_nodes_examined is > 0, then number_lymph_nodes_positive >= number_lymph_nodes_examined |
|No | 0 or left blank | Should be left blank |
|Not applicable | 0 or left blank | Should be left blank |
|No lymph nodes found in resected specimen | 0 or left blank | Should be left blank |
| Cannot be determined | 0 or left blank | Should be left blank |

**Comment by rosibaj** [comment]
Tested April 6th (comments on PR) so moving back to in progress

**Comment by rosibaj** [comment]
Included in Dictionary 1.8; migration confirmed on prod release.
