### ISSUE TITLE
🐛 Missing some stage groups in enum list

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#260]
## Describe the bug
Stage groups `Stage IVS` and `Stage IVE` exist in script but are missing in the enum list. Update enum list and verify they match the groups in the script.

Example: 
![image](https://user-images.githubusercontent.com/4992044/113741179-64e41d00-96cf-11eb-868a-0946baa56535.png)
![image (1)](https://user-images.githubusercontent.com/4992044/113741192-66ade080-96cf-11eb-8e52-f734bfcfb972.png)

**Comment by rosibaj** [comment]
Included in Dictionary 1.8; migration confirmed on prod release.
