### ISSUE TITLE
Add script validation for line_of_treatment

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#261]
The `line_of_treatment` field is optional but should only be submitted if `is_primary_treatment` is `No` or `Unknown`. Add a script validation that allows the following:

|is_primary_treatment | line_of_treatment |
|--|--|
| No or Unknown | Allowed to have a value |
| Yes | Should be left empty |

**Comment by rosibaj** [comment]
Confirmed on Ulyssus Release May 10, 2021
