### ISSUE TITLE
Add script validation for hemotological_toxicity

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#262]
Add script validation that only allows `hemotological_toxicity` to be submitted if `toxicity_type` is `Hemotological`:

| toxicity_type | hemotological_toxicity |
|--|--|
| Hemotological | Allowed to be submitted |
| Non-hemotological | Should not be submitted |

**Comment by rosibaj** [comment]
Confirmed on Ulyssus Release May 10, 2021
