### ISSUE TITLE
Add exposure validation scripts

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#271]
Add validation scripts for:
tobacco-related fields:
- `tobacco_type` is required if donor has history of smoking. `tobacco_smoking_status` must be consistent with 'tobacco_type' (if `tobacco_type` is filled in, then `tobacco_smoking_status` should be one of the smoker categories).
- `pack_years_smoked`: should only be submitted if donor has history of smoking.

alcohol-related fields:
- `alcohol_type`: should only be submitted if donor has alcohol history and consumes alcohol (ie. `alcohol_consumption_category` is not missing or unknown or none).

exercise-related fields:
- If `exercise_intensity` is submitted, then `exercise_frequency` cannot be 'never'.

**Comment by rosibaj** [comment]
Migration to dictionary 1.10 confirmed on production.
