### ISSUE TITLE
Add New Schema: Biomarkers

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#278]
https://docs.google.com/spreadsheets/d/19uO0x8b_2pe64kWb7vt_ikcWfBcAGbovJY3N-wxcnsE/edit#gid=1129576486

**Comment by hknahal** [comment]
Script:
- If `submitter_specimen_id`, `submitter_primary_diagnosis_id` or `submitter_treatment_id` or `submitter_followup_id` is not submitted, then `test_interval` is required.

**Comment by hknahal** [comment]
- [ ] include two new fields for submitting ER and PR percentages. Discussions with breast cancer experts (EuCan) indicated this is an important field to collect. Verified with PBCP-GB that they collect these values and intend to submit them to ARGO.

- [ ] Update definitions to include descriptions of why certain tests are performed.

- [ ] Include references to LOINC.

**Comment by rosibaj** [comment]
https://docs.icgc-argo.org/docs/release-notes/dictionary-releases#release-111 

released dictionary confirmed
