### ISSUE TITLE
Complete Donor Scripts Based Validations 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#28]
Currently all scripts listed in the dictionary are placeholders.  We need to update these to include real script based validation. 

An example script is here: https://wiki.oicr.on.ca/display/icgcargotech/Validation+Script+Template 

For the sample_registration file (https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/donor.json), please implement the following script  based validations in the dictionary: 

- [ ] 1) Add script validation to `cause_of_death` 
- This field should be filled in if vital_status=deceased 

- [ ] 2) Add the correct tags to the dictionary schema so they will appear in the Dictionary viewer.  A guide for tags can be found here: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=134938807

**Comment by wajiha-oicr** [comment]
The script has been added and performs the validation. However, the error message from the script doesn't show up in the UI ([see bug report](https://github.com/icgc-argo/argo-dictionary/issues/35)). 

Our theory is that the latest version of clinical should fix this issue.

**Comment by rosibaj** [comment]
Tested on QA - was not able to upload a file with the incorrect scenarios ( Alive + cause value, deceased + no cause valu) and was able to for the correct combinations. 

Thanks @wajiha-oicr !!!
