### ISSUE TITLE
Complete AJCC Script Based Validation across all examples

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#29]
Currently all scripts listed in the dictionary are placeholders.  We need to update these to include real script based validation. 

An example script is here: https://wiki.oicr.on.ca/display/icgcargotech/Validation+Script+Template 

There is one field that will use the same script across multiple files.  This is the clinical staging system and its associated fields. 

(https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/donor.json), please implement the following script  based validations in the dictionary: 

- [ ] 1) Create the tumor staging script that can be used across multiple files 
For the `staging_system` field, when any `AJCC` value is selected, then the `t_category`, `n_category`, and `m_category`, `stage_group`, `stage_suffix` fields are required to be filled in. 
- NOTE: not all file schema `staging_system` groupings contain `stage_group` &`clinical_stage_suffix` fields.
- [ ] 2) Assign the script to the correct fields in `follow_up`, `primary_diagnosis`, and `specimen` schemas
- [ ] 3) Add the correct tags to the dictionary schemas so they will appear in the Dictionary viewer.  A guide for tags can be found here: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=134938807

**Comment by wajiha-oicr** [comment]
Hi, I've been able to identify the following fields with the word staging system in their names:

- **follow_up.json**

    - `recurrence_tumour_staging_system`
    - `posttherapy_tumour_staging_system`

- **primary_diagnosis.json**

    - `clinical_tumour_staging_system`

- **specimen.json**

    - `pathological_tumour_staging_system`

Just want to confirm, will this script apply to each of these 5 fields? Am I missing any?

**Comment by wajiha-oicr** [comment]
Also, are there recent tsv sample files available for these schemas? Particularly [specimen.tsv](https://github.com/icgc-argo/argo-clinical/blob/master/sampleFiles/specimen.tsv) and [primary_diagnosis.tsv](https://github.com/icgc-argo/argo-clinical/blob/master/sampleFiles/primary_diagnosis.tsv); I'm not seeing any columns for the m, n, t, or stage fields.

**Comment by rosibaj** [comment]
@wajiha-oicr Yes, those are all the correct spots!

**Comment by wajiha-oicr** [comment]
@rosibaj , will the fields (i.e t,n,m category, stage group, stage suffix) eventually get codelists for which values are permitted? Or can the user enter any string they like?

Wondering if I need to check for empty strings or not; when there's a codelist that's already taken care of.

**Comment by rosibaj** [comment]
@wajiha-oicr They will NOT have a codelist, but the will probably have a regex.  An empty string should not be allowed for now: 

Here is a list of possibilities for the TNM scenarios that need to be codified into regex: 
```
T[0-4]
T[0-4][a-e]
T[0-4][a-e][0-2]
T[0-4][a-e][mi]
TX
Ta
Tis
Tis \(DCIS\)
Tis \(LCIS\)
Tis \(Paget's\)

N[0-4]
N[0-4][a-c]
N1(bI|bII|bIII|bIV|mi)
N0 (i+)
N0 (i-)
N0 (mol-)
N0 (mol-)
NX

M[0-2]
M[0-2][a-c]
MX
cM0 \(i+\)
```

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr They will NOT have a codelist, but the will probably have a regex. An empty string should not be allowed for now:
> 
> Here is a list of possibilities for the TNM scenarios that need to be codified into regex:
> 
> ```
> T[0-4]
> T[0-4][a-e]
> T[0-4][a-e][0-2]
> T[0-4][a-e][mi]
> TX
> Ta
> Tis
> Tis \(DCIS\)
> Tis \(LCIS\)
> Tis \(Paget's\)
> 
> N[0-4]
> N[0-4][a-c]
> N1(bI|bII|bIII|bIV|mi)
> N0 (i+)
> N0 (i-)
> N0 (mol-)
> N0 (mol-)
> NX
> 
> M[0-2]
> M[0-2][a-c]
> MX
> cM0 \(i+\)
> ```

I see, thanks. I'm assuming we will work on creating the validations for those fields as part of a separate ticket.

**Comment by rosibaj** [comment]
@wajiha-oicr yes, thats a future update :) list is still being verified.
