### ISSUE TITLE
Allow multiple submitter_donor_id entries in Biomarker table

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#302]
Currently in QA, the system does not allow multiple submitter_donor_id entries in the Biomarker table. 

## Example:
- Patient had biomarker tests done at the time of primary diagnosis. They were ER+, PR- and HER-.
- Patient was followed up 2.5 years later and found to have local recurrence. Biomarker tests were done at that time and they were ER+, PR- and HER+ this time.

[biomarker_v108.0_two_donor_ids.txt](https://github.com/icgc-argo/argo-dictionary/files/6710024/biomarker_v108.0_two_donor_ids.txt)

program_id | submitter_donor_id | submitter_specimen_id | submitter_primary_diagnosis_id | submitter_treatment_id | submitter_follow_up_id | test_interval | ca19-9_level | crp_levels | ldl_level | anc | alc | brca_carrier | er_status | er_allred_score | her2_ihc_status | her2_ish_status | pr_status
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HNAHAL-CA | Pat-1 | Sp-1 | PD-1 |   |   |   |   |   |   |   |   | BRCA1  | Positive | Total ER Allred score of 7 | Negative |   | Negative
HNAHAL-CA | Pat-1 |   | PD-1 |   | FL-2 |   |   |   |   |   |   |  BRCA1 | Positive | Total ER Allred score of 7 | Positive |   | Negative

The second entry is currently not allowed.
```
You are trying to submit the same [submitter_donor_id] in multiple rows. [submitter_donor_id] can only be submitted once per file.
```

## Possible Solution
Combination of `submitter_donor_id` + one of [`submitter_specimen_id`, `submitter_primary_diagnosis_id`, `submitter_treatment_id`, `submitter_followup_id`, `test_interval`] should be unique.

The purpose of having one of [`submitter_specimen_id`, `submitter_primary_diagnosis_id`, `submitter_treatment_id`, `submitter_followup_id`, `test_interval`] is so we know when the biomarker tests were done in the patient's cancer timeline. 

Hardeep will implement validation script that ensure  the following:
- If `test_interval` is submitted, then [`submitter_specimen_id`, `submitter_primary_diagnosis_id`, `submitter_treatment_id`, `submitter_followup_id`] should not be submitted.
- If one of [`submitter_specimen_id`, `submitter_primary_diagnosis_id`, `submitter_treatment_id`, `submitter_followup_id`] is submitted, then `test_interval` should not be submitted.

**Comment by rosibaj** [comment]
Issue moved to [icgc-argo/argo-clinical #713](https://github.com/icgc-argo/argo-clinical/issues/713) via [**ZenHub**](https://www.zenhub.com/)
