### ISSUE TITLE
Make 'immunotherapy_type' field Core

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#304]
Currently the 'immunotherapy_type' field is marked as 'Extended' because the `"core": true` is missing in the `meta` section. Will need to update schema to include this so it is a core field.

**Comment by rosibaj** [comment]
https://docs.icgc-argo.org/docs/release-notes/dictionary-releases#release-111 

released dictionary confirmed

**Comment by rosibaj** [comment]
https://docs.icgc-argo.org/docs/release-notes/dictionary-releases#release-111 

released dictionary confirmed
