### ISSUE TITLE
Add AJCC 6th Edition to staging system field

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#310]
The pancreatic ARGO programs indicated they use AJCC 6th edition (we currently have the 7th and 8th (current) editions). 

Include:
- controlled terminology for T, N and M fields
- controlled terminology for staging fields

**Comment by hknahal** [comment]
TNM 6th edition valid stage groups: https://docs.google.com/spreadsheets/d/1w3lgGVJimg8BCL80-R5wzwztxxZrnlNt85gmx2uOwR0/edit#gid=157995698

**Comment by hknahal** [comment]
While the TNM categories are similar in AJCC 7th and 8th editions, there are some differences with the AJCC 6th edition which will need to be taken into account:
- There is no 'MX' designation in AJCC 7th or 8th editions. The 'MX' designation was last used in the AJCC 6th edition. This means that if clinical or pathological tumour staging system is AJCC 7th or 8th edition and an 'MX' category is submitted in the *_m_category field, then the validation should fail. The 'MX' category is only valid if the staging system is AJCC 6th edition.
- There are several N categories ('N0(i-)','N0(i+)','N0(mol-)','N0(mol+)','N4') that are not applicable in clinical_n_category when the clinical staging system is AJCC 6th edition. This means that if for example 'N4' is submitted in the clinical_n_category when the clinical_staging_system is 'AJCC 6th edition', then the validation should fail.

**Comment by akachru-github** [comment]
Deployed and tested in QA

**Comment by kcullion** [comment]
looks good on netlify docs dictionary link
