### ISSUE TITLE
Update controlled terminology for anatomical_site_irradiated

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#315]
Update controlled terminology for `anatomical_site_irradiated` field in Radiation table, so it is in line with controlled terminology used by Cancer Care Ontario: https://ext.cancercare.on.ca/ext/databook/db2021/Appendix/Appendix_1.15_-_Body_Region_Codes_.htm The current controlled terminology used by Cancer Care Ontario has been updated to include more granularity. For example, the original controlled terminology used by Cancer Care Ontario was using the term "Thorax" and was missing the terms "Chest" which is applicable to Breast Cancer. The term "Extremities" has been split into "Lower Limb" and "Upper Limb". "Head-Neck" has been separated into two terms "Head" and "Neck". This is in keeping with the TCA Working Group's recommendation to keep this terminology very general (they did not recommend using ICD-O-3 codes for this field). This generalized list of terms can be mapped to mCODE's (SNOMED) terminology as well (RadiationTargetBodySiteVS)

Terms used in current CCO:

ABDOMEN
BODY
CHEST
HEAD
LOWER LIMB
NECK
PELVIS
SKIN
SPINE
UPPER LIMB

Older CCO terminology:
thorax (keep)
brain (keep)
- extremities (replaced by upper and lower limb)
- bone (too general)
- head-neck (split into head and neck)
liver (keep)
peritoneum (radiation is administered in abdomen area)
lung (keep)

New List:
ABDOMEN
BODY
BRAIN
CHEST
HEAD
LIVER
LOWER LIMB
LUNG
NECK
PELVIS
SKIN
SPINE
THORAX
UPPER LIMB

**Comment by kcullion** [comment]
Tested in Staging, and all of these values validate as expected:
```
Older CCO terminology:
thorax (keep)
brain (keep)

extremities (replaced by upper and lower limb)
bone (too general)
head-neck (split into head and neck)
liver (keep)
peritoneum (radiation is administered in abdomen area)
lung (keep)
```

**Comment by kcullion** [comment]
looks good in netlify docs site

**Comment by hknahal** [comment]
Added to dictionary version 1.13
