### ISSUE TITLE
Add a note about why comorbidity_type_code is "Conditional"

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#319]
Add a note explaining why the `comorbidity_type_code` field is `Required` and `Conditional`

The reason the `comorbidity_type_code` field is Conditional is because its value depends on the value of prior_malignancy. If `prior_malignancy` is `Yes` , then an ICD-10 code that starts with `C` or `D` is expected in the `comorbidity_type_code` field (these are ICD-10 codes for cancer). If however a non-cancer ICD-10 code is submitted when `prior_malignancy` is `Yes` (for example, it's submitted as  E10 for diabetes), then the clinical validation will fail because it expects an ICD-10 code for cancer. The `comorbidity_type_code` field is required because it requires either a cancer or non-cancer ICD-10 code.

**Comment by akachru-github** [comment]
Deployed and tested in QA

**Comment by kcullion** [comment]
this is showing up in the netlify preview of the new dictionary on the docs site!

**Comment by hknahal** [comment]
Deployed in Dictionary version 1.13
