### ISSUE TITLE
Add optional laterality field in Primary Diagnosis and Specimen schemas

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#324]
Based on discussions with Lincoln and Brandon regarding EuCanCan's request, we will add an optional clinical field related to laterality in the Primary Diagnosis and Specimen tables. Confirmed that ARGO Breast Cancer program (PBCP-GB) collects specimen and imaging laterality clinical information.

**Comment by hknahal** [comment]
Specimen:
Field name: "specimen_laterality"
Definition: For tumors in paired organs, designates the side on which the specimen was obtained.

Controlled terminology:
Left
Right
Unknown

NOTE: Did not include "Bilateral" as its not clear how a single specimen can be from both the left and right side of the body.

**Comment by kcullion** [comment]
@hknahal I tested this ticket using these files https://drive.google.com/drive/folders/1U1-agOMFf5vaOpq8lax-IZF1Rndibh1W?usp=sharing

I was able to optionally add values in for the new fields
<img width="780" alt="dictionary324-primary-diag" src="https://user-images.githubusercontent.com/18424138/139723231-7ccae973-2da6-4a02-8ba3-d60031e09570.png">
<img width="946" alt="dictionary324-specimen" src="https://user-images.githubusercontent.com/18424138/139723233-fa503d22-4bc2-4c70-888a-ad84f6902e82.png">

**Comment by kcullion** [comment]
This works for me in STAGING. I was able to submit a primary diagnosis file, one row had a value for laterality and one didn't. And a specimen file, one row had a value for specimen_laterality and one didn't. Submission was successful. Also download the new template files and I see those two fields present in them.

**Comment by kcullion** [comment]
reviewing netlify link and these were successfully added to new dictionary docs

**Comment by hknahal** [comment]
Deployed in Dictionary version 1.13
