### ISSUE TITLE
Add Duke, Jewett and Clark staging systems

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#325]
Based on discussions with Lincoln and Brandon regarding EuCanCan's dictionary, we will add the following staging systems to the *_staging_system fields in the ARGO dictionary:

- Jewett Staging System (fBladder Cancer)
- Duke Staging System (Colorectal Cancer)
- Clark's Staging System (Melanoma)

**Comment by hknahal** [comment]
Dukes' Staging System is a pathological staging system (will not be included in clinical_staging_system)
Reference:  SEER https://training.seer.cancer.gov/staging/systems/schemes/duke.html

- Add 'Dukes' staging system' to 'pathological_staging_system' codelist
- Add following terms to 'pathological_stage_group' codelist:
Dukes' A
Dukes' B
Dukes' C
Dukes' D

**Comment by hknahal** [comment]
@b-f-chan No, this ticket hasn't been released yet. It wasn't as urgent as the other tickets, so will address this for a later dictionary Release.

**Comment by Buwujiu** [comment]
Min scope is to add Jewett Staging System (fBladder Cancer) and Duke Staging System (Colorectal Cancer) into the dictionary.

**Comment by Buwujiu** [comment]
Not high priority right now, Hardeep will focus on dictionary proposals first.
