### ISSUE TITLE
change `radiation_therapy_dosage` to number, not integer 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#326]
- `radiation_therapy_dosage` should be number, not integer to allow for decimal values 
- add a range validation to reflect accurate values in Gy, not cGy

**Comment by hknahal** [comment]
Tested in QA using version `113.5`

**Comment by kcullion** [comment]
Tested in Staging, and was able to submit a decimal value for this field
![image.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/304a8a4d-f184-48b2-b8ec-973c6a07c738)

**Comment by kcullion** [comment]
reviewed netlify link for dictionary and this was changed to NUMBER

**Comment by hknahal** [comment]
Deployed in Dictionary version 1.13
