### ISSUE TITLE
Add Note: Clarification on biomarker id fields that they should submit one-of or test interval 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#327]
![image](https://user-images.githubusercontent.com/15824252/133467882-0fd13fa1-eb13-4802-b895-8023e88fdbe5.png)

**Comment by kcullion** [comment]
reviewed the netlify link and these notes are added!

**Comment by hknahal** [comment]
Deployed in Dictionary version 1.13
