### ISSUE TITLE
Remove 'unknown' from vital_status controlled terminology

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#329]
The 'vital_status' field is a required field and the only required field with 'unknown' in its controlled terminology. It's likely the controlled terminology was adopted from ICGC's 'vital_status' field. However, to ensure consistency with other required fields in the ARGO dictionary, the 'unknown' term will be removed from 'vital_status'. Since we are planning to implement clinical exceptions in the near future anyways, the 'vital_status' can be considered for a clinical exception if it is unknown for valid reasons.

**Comment by kcullion** [comment]
This works for me, I get an error when I try to submit a donor.tsv file with the value "unknown"
![Screen Shot 2021-11-16 at 12.21.57 PM.png](https://images.zenhubusercontent.com/5a5f5bcd4b5806bc2bc31a86/2ff63e02-faf3-49ac-9eb8-5763c1e17ca4)

**Comment by kcullion** [comment]
reviewed the netlify link for Hardeep's new dictionary and this value has been removed

**Comment by hknahal** [comment]
Deployed in Dictionary version 1.13
