### ISSUE TITLE
Notes Updates

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#337]
There are a few fields in the dictionary that require some clarifications in the 'description' or 'notes' fields. These include the following:

"age_at_menarche":
- Update "description" to include "in years" so it's consistent with other age-related field descriptions: Indicate the donor's age, **in years**, at which the first menstruation event occurred.

"number_lymph_nodes_examined": 
- Add following to "notes": This field is only required if 'lymph_nodes_examined_status' is 'Yes'

"percent_tumour_cells"
"percent_proliferating_cells"
"percent_inflammatory_tissue"
"percent_stromal_cells"
"percent_necrosis"
- Indicate what these fields are conditional on: "This field should only be submitted if the specimen is tumour"\

"Biomarker" schema description:
- Clarify how information in this table should be submitted. Update table description to "_Each row should include one or more biomarker test(s) associated with a particular clinical event (submitter_specimen_id, submitter_primary_diagnosis_id, submitter_treatment_id or submitter_follow_up_id field). If the biomarker test is not associated with a particular clinical event, then indicate the time interval at which the biomarker test was performed (test_interval field)._"

**Comment by kcullion** [comment]
reviewing the netlify link for @hknahal 's dictionary release and all of these notes are present

**Comment by hknahal** [comment]
Deployed in Dictionary version 1.13
