### ISSUE TITLE
Add new permissible value to `specimen_type`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-dictionary#340]
Add "Malignant neoplasm without specification of site” to permissible enum list of `specimen_type`.

Add some brief context here:
A question from the POG group in Canada re data clinical submission. Their cases are metastatic disease explicitly and have questions where the specimen_type and cancer_type_code is Unknown (genomic analysis was not able to definitively call a tumour type nor if the site is primary or metastatic). They could probably enter the cancer_type_code in as C80 (ICD 10 malignant neoplasm, unspecified site) but we currently have no suitable value for specimen_type. We either grant an exception for these cases or we introduce a permissible value such as malignant neoplasm without specification of site within specimen_type. 

FYI, the current `specimen_type` enum list is
```
Cell line - derived from normal
Cell line - derived from tumour
Cell line - derived from xenograft tumour
Metastatic tumour - additional metastatic
Metastatic tumour - metastasis local to lymph node
Metastatic tumour - metastasis to distant location
Metastatic tumour
Normal - tissue adjacent to primary tumour
Normal
Primary tumour - additional new primary
Primary tumour - adjacent to normal
Primary tumour
Recurrent tumour
Xenograft - derived from primary tumour
Xenograft - derived from tumour cell line
```

**Comment by hknahal** [comment]
It's not clear what `"without specification of site"` means in `"Malignant neoplasm without specification of site"`. This could be mistaken for tissue source or primary site, which are both collected in different (required) fields (`specimen_tissue_source` and `primary_site` fields, respectively). 

The controlled vocabulary for `specimen_type` indicates the **_type_** of tumour or normal specimen. Will add the term  `"Tumour - unknown if derived from primary or metastatic tumour"` to `specimen_type` field to ensure consistency with other terms in the controlled vocabulary (we actually do a grep on this field for "tumour" to validate consistency between `tumour_normal_designation` and `specimen_type`)

**Comment by b-f-chan** [comment]
@hknahal to investigate during Apr 21 - May 5 sprint

**Comment by b-f-chan** [comment]
Need a ticket for SONG schema to add term to allowed list --> Not a code change, but need to update the schema; Bioinfo can take this up

**Comment by b-f-chan** [comment]
Merged to PR, but won't close until dictionary actually released

**Comment by hknahal** [comment]
SONG changes were not deployed yet, so moved this ticket to Dictionary 1.17

**Comment by b-f-chan** [comment]
@Buwujiu - Let's make sure this gets handled/discussed at planning tomorrow

**Comment by Buwujiu** [comment]
Once we deploy song to prod, we can move this forward.

**Comment by b-f-chan** [comment]
Still waiting for Song deploy

**Comment by hknahal** [comment]
Tested in QA using dictionary version 124.1. Was able to submit `Tumour - unknown if derived from primary or metastatic` for `specimen_type` field.

**Comment by puneet-oicr** [comment]
Will be part of 1.17

**Comment by hknahal** [comment]
Tested in Staging using Dictionary 1.17 and works as expected. Able to submit the value `Tumour - unknown if derived from primary or metastatic` for the `specimen_type` field.
