### ISSUE TITLE
Add additional surgery type terms related to thyroid cancer to 'surgery_type' field

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#355]
The PTC-SA program has requested additional surgery type terms related to thyroid cancer to be added to the `surgery_type` field in the 'Surgery' schema:

Total thyroidectomy (Reference: UMLS CUI: [C0193788](https://uts.nlm.nih.gov/uts/umls/concept/C0193788))
Near-total thyroidectomy (Reference: UMLS CUI: [C2148001](https://uts.nlm.nih.gov/uts/umls/concept/C2148001))
Subtotal thyroidectomy (Reference: UMLS CUI: [C0193790](https://uts.nlm.nih.gov/uts/umls/concept/C0193790))
Hemithyroidectomy (Reference ICD-9-CM [06.2](https://uts.nlm.nih.gov/uts/umls/vocabulary/MTHICD9/06.2))

**Comment by Khondaker97** [comment]
There's another terms along the mentioned above-
- Lobectomy

And some techniques that used for thyroidectomy:
- Standard thyroidectomy
- Endoscopic thyroidectomy
- Robotic thyroidectomy

**Comment by b-f-chan** [comment]
Tested in QA and ready for release today.  This is the only scope for Dictionary 1.15 and unblock the thyroid cancer project.
