### ISSUE TITLE
Add "lost_to_followup"

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#358]
**NOTE**: This is still work in progress

**What is lost to followup?**
A donor is considered lost to follow-up when they can no longer be contacted for follow-up procedures. Examples of possible reasons why a donor can be lost to follow-up could be because the donor completed the study, or the donor's whereabouts are unknown (ie. they moved), or they withdrew from a study, or they were discharged to palliative care.

**Why do we need to capture this?**
If a donor is lost to follow-up, it means their vital status (Alive/Deceased) is no longer known. Donors lost to follow-up often have a different prognosis than those who complete a study or are followed until death, and this can impact survival estimates.

**Example**:
A donor had their last follow-up 89 days after their date of primary diagnosis. An attempt to do a follow-up was done 170 days after their date of primary diagnosis, but the donor moved and can no longer be contacted. In a clinical timeline, the donor would be indicated as "Lost to follow up" after their last Follow Up event (FO1133) because that was the last time they were known to be alive. There are no clinical events after this time point.

![image](https://user-images.githubusercontent.com/4992044/186997461-38b6d34f-85c7-4af7-981e-66b1bef4b569.png)

### Use Case:

This is an actual use case from the Mutographs program. A donor was diagnosed with esophageal cancer (cancer_type_code = C15). They underwent surgery treatment 15 days after their date of primary diagnosis, but they were lost to follow up soon after because the hospital couldn't contact the donor and they don't know the status of the donor's cancer after surgery (ie. no follow ups were ever done).

**Possible Solution 1:**
Definition of "lost_to_followup" field: "Indicate if donor was declared lost to follow-up after this <insert clinical event (eg. primary diagnosis, treatment, followup)>."

Add "lost_to_followup" field in each clinical event (Primary Diagnosis, Treatment, Follow Up tables). When a donor becomes lost to follow-up, they can go back to the last clinical event when the patient was known to be alive, and submit "lost_to_followup" = "Yes". If they are not lost to follow up, the data submitter can just leave this field blank. 
To indicate this use case, the data submitter would go back to the donor's last treatment ("TR_01") and update the field "lost_to_followup" = "Yes". This tells us the donor was declared lost to follow up after this treatment. We know they were last known to be alive 15 days after their primary diagnosis (treatment_start_interval). 

![image](https://user-images.githubusercontent.com/4992044/186998676-b23d372d-6c18-4eba-a9a0-4c5179164f3e.png)

**Required validation:**
- Only one "lost_to_followup" field can be submitted as "Yes".
- If "lost_to_followup" = "Yes" is submitted, then if any other clinical events are submitted (Primary Diagnosis, Treatment, Follow Up), the respective time interval fields (age_at_diagnosis, treatment_start_interval, interval_of_followup) cannot exceed the interval of time field for the clinical event in which the the "lost_to_followup" field was submitted as "Yes". In the above example, the data submitter cannot submit a subsequent Treatment or Follow Up entry that occurs after 15 days (treatment_start_interval for TR_01). If they do, then the system should report and error and require the data submitter to review their submission. It's possible the hospital was able to find the donor later on and were able to do more treatment/follow ups. In this case, the data submitter would need to update the "lost_to_followup" field they had originally submitted in the Treatment table (TR_01) to empty. 

**Possible Solution 2:**
Definition of "lost_to_followup" field: "Indicate if donor was declared lost to follow-up after this <insert clinical event (eg. primary diagnosis, treatment, followup)>."
Definition of "lost_to_followup_after_clinical_event": "Indicate the unique submitter_primary_diagnosis_id or submitter_treatment_id or submitter_follow_up_id of the clinical event after which the donor was declared lost to follow up."

Add "lost_to_followup" field and "lost_to_followup_after_clinical_event" in Donor table only. If "lost_to_followup" = "Yes", then require data submitter to submit the identifier for the clinical event (submitter_primary_diagnosis_id or submitter_treatment_id or submitter_follow_up_id) after which the donor was declared lost to follow up.
In this solution, the data submitter would update "lost_to_followup" = "Yes" and "lost_to_followup_after_clinical_event" = "TR_01" in the Donor table.

![image](https://user-images.githubusercontent.com/4992044/186998721-cbedcdb2-df16-484d-9aa7-82053824c331.png)

**Required validation:**
- Check if the submitted identifier in "lost_to_followup_after_clinical_event" exists in either "submitter_primary_diagnosis_id", "submitter_treatment_id" or "submitter_followup_id" in the Primary Diagnosis, Treatment, and Follow Up tables respectively. If it does not, then report an error message indicating the identifier does not exist.
- If "lost_to_followup" = "Yes" is submitted, then if any other clinical events are submitted (Primary Diagnosis, Treatment, Follow Up), the respective time interval fields (age_at_diagnosis, treatment_start_interval, interval_of_followup) cannot exceed the interval of time field for the clinical event referenced in "lost_to_followup_after_clinical_event". In the above example, the data submitter cannot submit a Follow Up entry that occurs after 15 days (treatment_start_interval for TR_01). If they do, then the system should report and error. It's possible the hospital was able to find the donor later on and were able to do more treatment/follow ups. In this case, the data submitter would need to update the "lost_to_followup" field they had originally submitted in the Treatment table (TR_01) to empty.
 
**Why not add "Unknown" or "Lost to Follow up" to "vital_status"?**
Because we still want to know what interval of time the donor was alive. Updating "vital_status" to "Unknown" or "Lost to Follow up" means we no longer know when the donor was last known to be alive, and when the donor was declared lost to follow up (we need a time interval associated with each). In the above example, we know the patient was known to be alive for 15 days after their date of primary diagnosis, but after their last treatment (15 days), they were declared lost to follow up, meaning it's not known whether they are alive or deceased after that.

**Comment by Buwujiu** [comment]
@hknahal questions for solution 1: what's the meaning of "lost_to_followup" field in a followup table? I understand a "lost_to_followup" in the primary diagnosis table means the donor is lost after this diagnosis, same for treatment. But isn't followup table already tracking subsequent primary diagnosis and treatments, so why follow up on a followup? Is it because you can have a "standalone" followup which isn't related to any primary diagnosis or treatment?

**Comment by hknahal** [comment]
> 1. what's the meaning of "lost_to_followup" field in a followup table? I understand a "lost_to_followup" in the primary diagnosis table means the donor is lost after this diagnosis, same for treatment. But isn't followup table already tracking subsequent primary diagnosis and treatments, so why follow up on a followup? Is it because you can have a "standalone" followup which isn't related to any primary diagnosis or treatment?

The Follow Up table is any point of contact with the donor after primary diagnosis where their disease status was assessed, so it's not tracking subsequent primary diagnoses or treatments. If a donor is diagnosed with a new second cancer, that information would go in the Primary Diagnosis table (as a new entry for that donor). If they have additional treatments, the new treatment information will go in the Treatment table. A follow-up could be for example, a scheduled appointment the donor has every 6 months to check that the cancer hasn't come back.  A follow up has to be related to a primary diagnosis because we're only interested in collecting information about follow-ups that are related to the donor's cancer. The follow-up could be related to a treatment, but not always. For example, a donor may have a follow-up appointment that is related to the completion of 6 months of chemotherapy treatment to find out if the treatment was successful. But sometimes the hospital loses contact with the donor (maybe they moved away), so they can't do subsequent follow up appointments to find out what their cancer disease status is. The "lost_to_followup" field in the Follow Up table means that the donor was unable to be contacted after their last successful follow-up (ie. it's a flag). Here's an example:

- A donor was diagnosed with cancer at age 55. They had a follow-up appointment on Oct 25, 2020, 120 days after they were diagnosed, and during this appointment the physician indicated their disease status was stable. To indicate this, the data submitter would submit an entry in the Follow Up table like this:

**Primary Diagnosis**
| submitter_donor_id | submitter_primary_diagnosis_id | age_at_diagnosis | cancer_type_code | 
|-- | -- | -- | -- | 
| DO_10 | PD_01 | 55 | C23 |

**Follow Up** 
| submitter_donor_id | submitter_follow_up_id | submitter_primary_diagnosis_id | interval_of_followup | disease_status_at_followup |
|-- | -- | -- | -- | -- |
DN_10 | FL_01 | PD_01 | 120 | Stable |

- The hospital attempted to contact the donor again on Jan 18, 2021 to do another follow-up, but they could not contact the donor anymore, maybe because they moved away (meaning they were lost to follow-up). The last time the donor was known to be alive was at their last successful follow-up (FL_01). To indicate this, the data submitter would update the donor's last follow-up entry with the "lost_to_followup" = "Yes":

**Follow Up** 
| submitter_donor_id | submitter_follow_up_id | submitter_primary_diagnosis_id | interval_of_followup | disease_status_at_followup | lost_to_followup | 
|-- | -- | -- | -- | -- | -- |
DN_10 | FL_01 | PD_01 | 120 | Stable | Yes |

We don't collect anything about the Jan 18, 2021 attempted follow-up because there is no information available for that unsuccessful follow-up. We don't know if the donor perhaps died in between Oct 25, 2020 and Jan 21, 2021. All we know is that they were last known to be alive at their last follow up (FL_01 which happened Oct 25, 2020) and after that they are declared lost to follow up.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

> 2. The second validation rules says age_at_diagnosis cannot exceed the interval of time field for the clinical event in which the the "lost_to_followup" field was submitted as "Yes". Does it mean they can't submit anymore primary diagnosis for this donor after the first age_at_diagnosis(in this example, it's age 55)?

Yes, it means that the data submitter shouldn't submit clinical information that happens after the clinical event in which they submitted "lost_to_followup" = "Yes". Using the above example, let's say the data submitter submits a new entry in the Primary Diagnosis table (PD_02) indicating that the donor was diagnosed with a new cancer (C50) 10 years after they were declared lost to follow up. This should result in an error:

**Primary Diagnosis**
| submitter_donor_id | submitter_primary_diagnosis_id | age_at_diagnosis | cancer_type_code | 
|-- | -- | -- | -- |
| DO_10 | PD_01 | 55 | C23 |
| DO_10 | PD_02 | 65 | C50 |

**Follow Up** 
| submitter_donor_id | submitter_follow_up_id | submitter_primary_diagnosis_id | interval_of_followup | disease_status_at_followup | lost_to_followup | 
|-- | -- | -- | -- | -- | -- |
| DN_10 | FL_01 | PD_01 | 120 | Stable | Yes |

```Error message: You are trying to submit clinical information after a donor was declared lost to followup. Please review your submission.```

It's possible the data submitter entered the information incorrectly. Or it's possible the hospital was able to get in touch with the donor again 10 years later, and that's when they found a second cancer. If that is the case, then to correct this, the data submitter could remove "lost_to_followup" = "Yes" in the "FL_01" entry in the Follow Up table since the donor is no longer declared lost to follow up.

> For solution 2, can we remove "lost_to_followup" from donor table and only keep "lost_to_followup_after_clinical_event"? If "lost_to_followup_after_clinical_event" is not blank, we know for sure "lost_to_followup" is yes.

Yes, that's a good point! We can remove the "lost_to_followup" in solution 2, so we just have "lost_to_followup_after_clinical_event"

**Comment by hknahal** [comment]
### Dictionary changes required

1. Add new optional field called `lost_to_followup_after_clinical_event` in `Donor` schema:

| Field | Description | Data Tier | Attributes | Type |
|--|--|--|--|--|
| lost_to_followup_after_clinical_event | If the donor became lost to follow up, indicate the identifier of the clinical event (eg. submitter_primary_diagnosis_id, submitter_treatment_id, submitter_follow_up_id) after which the donor became lost to follow up. | ID |  | TEXT |

2. Add a validation that checks the following:
- If `vital_status` = `Deceased` and `lost_to_followup_after_clinical_event` is submitted (has a valid ID), then validation should fail because it is not possible for the donor to be lost to follow up if they are known to be deceased.

**Example of valid submission:**
Donor was lost to follow up after their surgery treatment (TR_01)
This means the donor was last known to be alive 15 days after their primary diagnosis.
![valid_ltf](https://user-images.githubusercontent.com/4992044/199822884-f310fc08-c5eb-4941-9bd4-279f44ff4238.png)

**Example of invalid submission:**
Since the `lost_to_followup_after_clinical_event` field is submitted, then it's not possible to know that the donor's vital_status is `Deceased`.
![invalid_ltf](https://user-images.githubusercontent.com/4992044/199823503-3a981991-05ba-48f7-85e3-5324a2167ad8.png)
--> Either the data submitter made an error submitting `vital_status` as `Deceased` instead of `Alive`, or the donor was found later on and known to be deceased, but the data submitter did not update the clinical submission by submitting blank for `lost_to_followup_after_clinical_event`.

### Clinical changes required:
If `lost_to_followup_after_clinical_event` is submitted:

1. The identifier submitted in the `lost_to_followup_after_clinical_event` must exist in the clinical submission in either the `submitter_primary_diagnosis_id` or `submitter_treatment_id` or `submitter_follow_up_id` field. This check will need to be done against the active submission and signed-off submission. If it does not match any of the existing IDs in the `submitter_primary_diagnosis_id` or `submitter_treatment_id` or `submitter_follow_up_id` fields, then the validation should fail and report an error message (eg. "The ID submitted in the 'lost_to_followup_after_clinical_event' does not exist in your clinical submission. Check your submission to ensure you submit the correct clinical event ID")

**Example of valid submission:**
The identifier submitted in the `lost_to_followup_after_clinical_event` field ("FL22") exists in the `submitter_follow_up_id` column in the `Follow up` schema. This means the donor was last known to be alive 170 days after their primary diagnosis (this is the "interval_of_followup" value for submitter_follow_up_id "FL22").
![valid_ltf_id](https://user-images.githubusercontent.com/4992044/199831331-d38682c7-73ab-48bf-b265-251f56aec3c4.png)

**Example of invalid submission:**
The identifier submitted in `lost_to_followup_after_clinical_event` ("TR_03") doesn't exist in any of the `submitter_primary_diagnosis_id`, `submitter_treatment_id` or `submitter_follow_up_id` fields.
![invalid_ltf_id](https://user-images.githubusercontent.com/4992044/199831546-95689897-74a2-4fe7-971c-5195b744562b.png)
Error Message: "The identifier 'TR_03' submitted in the 'lost_to_followup_after_clinical_event' does not exist in your clinical submission."

2. No additional entries are allowed to be in any of the clinical events where the new entry's time interval field is greater than the time interval associated with the ID in the `lost_to_followup_after_clinical_event` field. 

| Matching clinical ID for lost_to_followup_after_clinical_event ID | Time interval to check against |
|--|--|
| submitter_primary_diagnosis_id | age_at_diagnosis |
| submitter_treatment_id | [treatment_start_interval + treatment_duration |
| submitter_follow_up_id | interval_of_followup |

**Example 1 of invalid submission:**
The data submitter indicated the donor was lost to follow up after a follow up that happened 170 days after their primary diagnosis (`lost_to_followup_after_clinical_event` = "FL22").
The data submitter submits a new entry in the Treatment schema (last row highlighted in red text) where the donor has a new treatment (submitter_treatment_id = "TR33") that started 250 days after their primary diagnosis (the "treatment_start_interval" field). 
However, this does not make sense because the donor was lost to follow up before this (170 days after primary diagnosis). In this case, TR33.treatment_start_interval (250 days) is greater than FL22.interval_of_followup (170 days).

![invalid_ltf_submission](https://user-images.githubusercontent.com/4992044/199838903-3ea8eb1a-bcaf-45db-9e41-fd9927527bd9.png)

Error message: "You indicated the donor was lost to follow up 170 days after their primary diagnosis ("FL22"), but you submitted a new treatment ("TR33") that occurs after the donor was lost to follow up. If the donor was found later on, then update the "lost_to_followup_after_clinical_event" field to be empty."

**Example 1 of invalid submission:**
The data submitter indicated the donor was lost to follow up after a follow up that happened 170 days after their primary diagnosis (`lost_to_followup_after_clinical_event` = "FL22").

**Comment by b-f-chan** [comment]
May move this to Dictionary 1.17 to unblock 1.16 release

However, this fix would unblock Mutographs

**Comment by puneet-oicr** [comment]
Can't be released in Dictionary 1.16 due to a clinical dependency

**Comment by edsu7** [comment]
Dan is working on clinical implementation.

**Comment by Buwujiu** [comment]
Once the cross file validation is ready, will deploy the new dictionary to prod.

**Comment by hknahal** [comment]
Can close this ticket since it was released in Dictionary 1.19
