### ISSUE TITLE
Update treatment_setting to accommodate more additional terminology

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#363]
Current terminology consists of the following terms:

Adjuvant
Neoadjuvant
Metastatic
Not applicable (can only be submitted if no treatment)

Proposal to add new terms to accommodate additional clinical use cases. These additional terms are derived from CDISC (Clinical Data Interchange Standards Consortium). Reference NCIt [C124308](https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=22.08e&code=C124308&ns=ncit&type=relationship&key=null&b=1&n=0&vse=null):

Conditioning (Reference: NCIt [C188745](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C188745
) and [C156597](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C156597))
Induction (Reference: NCIt [C158876](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C158876))
Locally advanced (Reference: NCIt [C124451](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C124451
))
Maintenance (Reference NCIt [C15688](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C15688))
Mobilization (Reference: NCIt [C62604](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C62604
))
Preventative (Reference: NCIt [C124454](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C124454))
Radiosensitization (Reference: NCIt [C156596](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C156596
) and [C15464](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C15464
))
Salvage (Reference: NCIt [C15359](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C15359))

**Comment by puneet-oicr** [comment]
@b-f-chan Needs someone assigned for testing.

**Comment by puneet-oicr** [comment]
@b-f-chan Needs someone assigned for testing.

**Comment by hknahal** [comment]
Released in Dictionary version 1.16
