### ISSUE TITLE
Update treatment_intent field with additional terms

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#364]
Current terms:
Curative
Palliative

Proposed new terms to add. These would accommodate additional use cases. For example, neoadjuvant treatment is not always curative or palliative, sometimes it is used for down-staging (Guidance or Diagnostic intent). These terms are derived and referenced from [mCODE HL7](http://hl7.org/fhir/us/mcode/ValueSet-mcode-procedure-intent-vs.html):

Supportive
Diagnostic
Preventive
Guidance
Screening
Forensic

Update definition to "Indicate the purpose of a treatment, or the desired effect or outcome resulting from the treatment."
Original definition applied to Curative/Palliative which was used in mCODE as well. Definition was updated when terminology was expanded.

**Comment by puneet-oicr** [comment]
@b-f-chan Needs someone assigned for testing.

**Comment by hknahal** [comment]
Released in Dictionary version 1.16
