### ISSUE TITLE
Investigate submission of investigational drugs which do not exist in RxNorm

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#367]
Example: "Dovitinib" and "Celastrol" do not exist in [RxNorm](https://mor.nlm.nih.gov/RxNav/). 

Investigate:
- Whether drug exists in other drug databases. For example "Dovitinib" exists in other databases (https://go.drugbank.com/drugs/DB05928#external-links). 
- If drug exists in other database, do they have a publicly accessible API to query drug name for accession identifier?

**Comment by hknahal** [comment]
Proposed changes that were implemented in [MOH data model](https://docs.google.com/spreadsheets/d/17Azd7dIORYIXk-czIEYJW9gNGgr6_IDmjRv1F20bEIU/edit?usp=sharing) as well. 
|Field name | Data Tier | Attribute | Type | Description | Permissible Values|
|--|--|--|--|--|--|
| drug_reference_database | Core | Required | Indicate the reference drug database where drug name is found. | Text | RxNorm, PubChem, NCI Thesaurus |
|drug_name | Core | Required | Indicate the drug name as it exists in the database specified in the drug_reference_database. | Text |  | |
| drug_reference_identifier | Core | Required | Indicate the identifier from the "drug_reference_database" for the drug.  | Text | | |

Having generalized fields that are not specific to just RxNorm enable addition of new drug reference databases in the future, should they be required.

Similar to RxNorm, we can use an API for PubChem and NCI Thesaurus to validate the submitted "drug_name" and "drug_reference_identifier" fields.

To validate drug_name and drug_reference_identifier from PubChem, we can use PubChem's API:

Example:
| Field name |  Value | Validation | 
|--|--|--|
| drug_reference_database | PubChem | |
| drug_name | Celastrol | https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/Celastrol/cids |
| drug_reference_identifier | 122724 | https://pubchem.ncbi.nlm.nih.gov/compound/122724 |

To validate drug_name and drug_reference_identifier from NCI Thesaurus:
- Download latest tsv dump file of NCI Thesaurus from https://evs.nci.nih.gov/evs-download/thesaurus-downloads. Can load this file in DB and search on drug_reference_identifier and drug_name. 

Example:
| Field name |  Value |
|--|--|
| drug_reference_database | NCI Thesaurus |
| drug_name | Allogeneic iC9/CAR19/IL15-transduced CB-NK Cells | 
| drug_reference_identifier | [C148215](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C148215) |

Search "code" column for drug_reference_identifier" and check if "drug_name" matches any of the terms that exist in the "synonym" column.

**Comment by edsu7** [comment]
- data migration
- update validation
- new dictionary field?
  - extend databases based on MONSTAR's drug list
  - add new field to capture nonnamed drugs (i.e. honey)
-

**Comment by edsu7** [comment]
Current discussion:
- add new fields to capture drug databases outside for Rxnorm

Eventually:
- retire fields `drug_rxnormcui` and `drug_name` and migrate them under the new fields
- Migrate data as well

**Comment by edsu7** [comment]
After a bit of investigation, `drug_name` is validated with `drug_rxnormcui` api call. Validation for `drug_name` cannot be simply uncoupled.

See:
https://github.com/icgc-argo/argo-clinical/blob/f3f0a6fc606906d52784240f2c731e341cc8e7b0/src/submission/submission-service.ts

Testing in QA:
<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3VKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bffd21366c3ed8cdd2901d76d314c9983c8c5d3/image.png" alt="image.png" />

with file:
```
program_id	submitter_donor_id	submitter_treatment_id	drug_rxnormcui	drug_name	chemotherapy_drug_dose_units	prescribed_cumulative_drug_dose	actual_cumulative_drug_dose	dose_intensity_reduction	dose_intensity_reduction_event	dose_intensity_reduction_amount	
TEST-CA	DN290	TR-8	194000	Methotrexate	mg/m2	150	100	No		
```
