### ISSUE TITLE
Add additional treatment response critieria

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#378]
**Implementation:**

- Add new required field "response_to_treatment_assessment_method" with controlled terminology of additional methodologies. (eg. iRECIST, RANO, Cheson etc).
- Update existing "response_to_treatment" to include terms for each methodology listed in the "response_to_treatment_assessment_method" field.
- Add a validation rule that checks that the value submitted in “response_to_treatment” belongs to the method indicated in “response_to_treatment_assessment_method”.

**Rationale:**

- Based on discussions with the MOH Clinical Committee and ARGO CMD Working Group, some cancer types/cohorts use different terminologies than RECIST (ie. RANO for neuro-oncology, Cheson for lymphoma) or assign different criteria for the same terms (ie. RANO criteria for "stable disease" is different than criteria used by RECIST).
- This solution enables cross-comparison of response to treatment.
- Data submitters should follow guidance and definitions of each term as provided by each response to treatment assessment method. Example: Guidelines and definitions of terms in Cheson Oncology Response Criteria as provided by NCI Working Group on CLL: https://www.sciencedirect.com/science/article/pii/S0006497120611971?via%3Dihub

** New response criteria **
|RECIST | iRECIST | Cheson Oncology Response Criteria | Response Assessment in Neuro-Oncology (RANO) | AML Response Criteria | Physician Assessed Response Criteria |
|  -- | -- | -- | -- | -- | --
| Complete response | Immune complete response (iCR) | Complete remission | Complete response | Complete remission without measurable residual disease (CR MRD−) | Physician assessed complete response |
| Partial response | Immune partial response (iPR) | Partial remission | Partial response | Complete remission | Physician assessed partial response |
| Progressive disease | Immune unconfirmed progressive disease (iUPD) | Stable disease | Minor response | Complete remission with incomplete hematologic recovery (CRi) | Physician assessed stable disease |
| Stable disease | Immune confirmed progressive disease (iCPD) | Progressive disease | Stable disease | Morphologic leukemia-free state |  
| No evidence of disease (NED) | Immune stable disease (iSD) |   | Progressive disease | Partial remission |  
  |   |   |   | Primary refractory disease |  
  |   |   |   | Hematologic relapse (after CRMRD-, CR, CRi) |  
  |   |   |   | Molecular relapse (after CRMRD-) |  
  |   |   |   | Stable disease |  
  |   |   |   | Progressive disease |  

NOTE: The term "Progressive disease" is used rather than "Disease progression".

**Comment by puneet-oicr** [comment]
To follow up on the testing status @hknahal

**Comment by Buwujiu** [comment]
Tested in QA TEST-CA, working as expected!

**Comment by hknahal** [comment]
Released in Dictionary version 1.16
