### ISSUE TITLE
New specimen_type terms

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#392]
**Implementation:**

Based on discussions with MOH Clinical Committee and ARGO CMD Working Group, will add two new terms to `specimen_type` in the Sample Registration schema. This is to accommodate additional patient derived specimen types.

New terms:
Cell line – derived from metastatic tumour
Xenograft – derived from metastatic tumour

This will require updates to SONG as well: https://github.com/overture-stack/SONG/issues/790

**Comment by Buwujiu** [comment]
Hardeep will test in Prod.

**Comment by hknahal** [comment]
Can close this ticket since it was released in Dictionary 1.19
