### ISSUE TITLE
Add fields for drug dosage in immunotherapy table

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#393]
As pointed out by MOH Clinical Committee, fields for indicating drug dosage in the immunotherapy table are missing. These are the same fields found in the chemotherapy and hormone_therapy tables. Add the following fields:
- cumulative_drug_dosage
- prescribed_cumulative_drug_dosage

**Comment by Buwujiu** [comment]
Tested in QA TEST-CA, working as expected!

**Comment by hknahal** [comment]
Released in Dictionary version 1.16
