### ISSUE TITLE
Update `anatomic_site_progression_or_recurrence` field to accept multiple values

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#400]
Correct the `anatomic_site_progression_or_recurrence` field in the Follow Up table to accept multiple values. It currently only accepts one value. This issue was pointed out by the APGI-AU program

**Comment by puneet-oicr** [comment]
Almost ready

**Comment by hknahal** [comment]
Tested in Staging using Dictionary 1.17 and works as expected:

- Able to submit multiple values for `anatomic_site_progression_or_recurrence` field in the Follow Up table. 
- Examples of valid values: `C23.1|C50`
- Examples of invalid values: 
   `C12.5,C40` (invalid because codes need to be separated by a `|` character).
   `C34.2|D50` (invalid because ICD-10 code must start with `C`)
