### ISSUE TITLE
Proposed solution for making a clinical exception on the "prescribed_cumulative_drug_dose" and "actual_cumulative_drug_dose" 

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#409]
## Description
This potential solution involves leveraging the existing "chemotherapy_drug_dose_units" field to create a cross-field dependency in the dictionary on these Number fields. This solution would be similar to the ticket we discussed during the last sprint planning: [argo-dictionary-407](https://github.com/icgc-argo/argo-dictionary/issues/407) (PR [argo-dictionary/pull/408](https://github.com/icgc-argo/argo-dictionary/pull/408)).

An empty value for the "prescribed_cumulative_drug_dose" and "actual_cumulative_drug_dose" field will indicate the value (dose) is unknown (and we can state this in the documentation so it's clear). 

**Proposed cross-field validation check in dictionary:**
---> If "chemotherapy_drug_dose_units" == "Not applicable" (an exception value), then "prescribed_cumulative_drug_dose" and "actual_cumulative_drug_dose" fields should be empty.

Note: It's important the correct exception value of "Not applicable" is used for "chemotherapy_drug_dose_units" here (not "Unknown"), because "Not applicable" means the field is not relevant in the current context because the dose is missing (as per the definitions used by ARGO [here](https://docs.icgc-argo.org/docs/submission/clinical-data-validation-rules#submitting-missing-values-for-extended-clinical-fields)). 

**Example of a valid submission:** There is an exception on the "chemotherapy_drug_dose_units" field ("Not applicable") and the 2 dose fields are empty.
![example1](https://github.com/icgc-argo/argo-dictionary/assets/4992044/119c0336-8898-4ea9-9d37-95eca5d70578)

**Example of an invalid submission:** An enum value is submitted (mg/m2) for the "chemotherapy_drug_dose_units" field, but the 2 dose fields are left empty.
![example2](https://github.com/icgc-argo/argo-dictionary/assets/4992044/d2dcd9a4-752f-4cad-8bcd-36ac3647bc51)

**Comment by Buwujiu** [comment]
@joneubank will review the solution.

**Comment by joneubank** [comment]
This looks like a manageable solution Hardeep, happy to go through with it.  The only thing strange to me is the fact that we will have validation scripts that look for the 'Not applicable' value despite the dictionary stating that isn't an allowed value.  Is this a case where you want to make 'Not applicable' available to all submitters, or do you want them to still request an exception to use that value?

**Comment by hknahal** [comment]
Thanks @joneubank. We don't want to make "Not applicable" available as an enum value in the dictionary because we risk losing clinical data related to chemotherapy. We'll require programs to request a clinical exception, and if the clinical exception request is approved, then they'll be able to submit "Not applicable". This ensures that "Not applicable" is used in the correct context. I realize the dictionary validation script will be referencing a value that doesn't exist in the dictionary, so I can include a comment in the script indicating that section of the code is for clinical exceptions.

**Comment by hknahal** [comment]
Closing ticket. Released in Dictionary version 1.18
