### ISSUE TITLE
Allow treatment_start_interval=0 in treatment table

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-dictionary#417]
Ayelet from PACA-CA created a request that `treatment_start_interval` in treatment table should allow to be equal to 0 because date of surgery is the date of diagnosis. 
The change should be made to: https://github.com/icgc-argo/argo-dictionary/blob/develop/schemas/treatment.json#L124-L131

**Comment by joneubank** [comment]
This change creates ambiguous behaviour if we ever update `interval_of_followup` to also allow a value of 0. This logic should be clarified and its possible the clinical service validations need to be updated to match.

Relevant code block. This test would not be run if either interval is 0.
https://github.com/icgc-argo/argo-clinical/blob/develop/src/submission/validation-clinical/treatment.ts#L203

**Comment by lindaxiang** [comment]
I have communicated with the data submitter and no need for this request now. This ticket can be closed. @bhavikbhagat93
