### ISSUE TITLE
Allow `specimen_acquisition_interval` to accept negative numbers

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/argo-dictionary#432]
In the current data model, `specimen_acquisition_interval` indicates the interval between primary diagnosis and specimen acquisition in days. It is an integer larger than 0. 

However, for program MONSTAR, 
- They use date of enrolment as date of diagnosis
- Their tissue NGS is performed with archival tissue for the majority of cases, so sample collection is often performed prior to enrolment

Considering the specimen table can be expanded to collect any specimens associated with a donor not only related to one given diagnosis. We can allow the `specimen_acquisition_interval` to accept negative numbers.

Implementation
- remove the restrictions: https://github.com/icgc-argo/argo-dictionary/blob/develop/schemas/specimen.json#L152-L157

**Comment by edsu7** [comment]
tested in QA, waiting for Bhavik to test

**Comment by lindaxiang** [comment]
Addressed by PR: https://github.com/icgc-argo/argo-dictionary/pull/433

**Comment by edsu7** [comment]
Tested in QA.
PR merged

things left to do
- update dictionary and deploy in prod
