### ISSUE TITLE
Add new fields `drug_database`,`drug_id` and `drug_term`

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/argo-dictionary#435]
To address MONSTAR who will have drug treaments outside of Rxnorm, three new fields will be added to to [hormone](https://github.com/icgc-argo/argo-dictionary/blob/develop/schemas/hormone_therapy.json),[immuno](https://github.com/icgc-argo/argo-dictionary/blob/develop/schemas/immunotherapy.json) and [chemo](https://github.com/icgc-argo/argo-dictionary/blob/develop/schemas/chemotherapy.json):
- `drug_database`
- `drug_id`
- `drug_term`

API Validation to follow in separate ticket

**Comment by joneubank** [comment]
Relates to: https://github.com/icgc-argo/argo-dictionary/issues/367

**Comment by lindaxiang** [comment]
- [ ] The following 3 conditional fields are added 

|Field name | Data Tier | Attribute | Description | Type | Permissible Values|
|--|--|--|--|--|--|
| drug_database | Core | Conditional | Indicate the drug database where drug term is found. | Text | KEGG, PubChem, NCI Thesaurus |
|drug_term | Core | Conditional | Indicate the drug term as it exists in the database specified in the drug_database. | Text |  | |
| drug_id | Core | Conditional | Indicate the identifier from the "drug_database" for the drug.  | Text | | |

- [ ] The following 2 fields are changes from `Required` to `Conditional`
- `drug_rxnormcui` 
- `drug_name`

**Comment by lindaxiang** [comment]
Validations script has beed added to cover:

- [ ] If drug_rxnormcui is provided
    - drug_name is required
    - Drug_database, drug_term and drug_id should not be populated
- [ ] If drug_rxnormcui is not provided
   - Drug_name should not be populated
   - Drug_database, drug_term and drug_id should be populated

**Comment by lindaxiang** [comment]
Addressed by PR: https://github.com/icgc-argo/argo-dictionary/pull/437
