### ISSUE TITLE
🐛 post therapy tumour staging system is not dependent on disease_status_at_followup

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#52]
### Description of bug:
Post-therapy tumour staging system should not be dependent on whether the disease status is relapse or progression.

<img width="1417" alt="Screen Shot 2020-03-03 at 3 37 57 PM" src="https://user-images.githubusercontent.com/4992044/75824987-79d6da00-5d72-11ea-9f2e-de8b61fe45a5.png">

### Solution
We can remove the following script validations for posttherapy_tumour_staging_system:

https://github.com/icgc-argo/argo-dictionary/blob/master/references/validationFunctions/follow_up/posttherapy_tumour_staging_system.js#L2
https://github.com/icgc-argo/argo-dictionary/blob/master/references/validationFunctions/follow_up/posttherapy_tumour_staging_system.js#L3

**Comment by kcullion** [comment]
this works in QA now!

**Comment by rosibaj** [comment]
tested on prod - this is not listed as a requirement when uploading follow-up with relapse or progression on production.  lgtm!
