### ISSUE TITLE
🐛 The word "or" in the codelist values for tumour_grade make it appear as though there are 2 options 

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#55]
## Example of bug:
The codelist for "tumour_grade" when tumour_grading_system is "lymphoid neoplasms" looks like this:

```
low grade or indolent nhl
high grade or aggressive nhl
```
A data submitter may confuse the "or" as an option to submit either "low grade" or "indolent nhl". But they need to submit the whole phrase (ie. "low grade or indolent nhl"). If they submit just "low grade", the validation fails like this:

<img width="1336" alt="Screen Shot 2020-03-03 at 4 38 35 PM" src="https://user-images.githubusercontent.com/4992044/75825216-efdb4100-5d72-11ea-91a6-0db8e30f3210.png">

## Expected behaviour
Format the newline response to show this:

```
- `low grade or indolent nhl`
- `high grade or aggressive nhl`
```

**Comment by rosibaj** [comment]
this is now shoiwng as a bulleted list:

**Comment by rosibaj** [comment]
confirmed on prod dictionary lgtm
