### ISSUE TITLE
🐛 Dictionary label: tumour dependencies in specimen file

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-dictionary#56]
## Describe the bug
Some fields in the specimen file are dependent on if tumour_normal_designation = tumour
(in sample-registration file). This is not reflected in the dictionary labels.
<img width="972" alt="Screen Shot 2020-03-04 at 9 30 28 AM" src="https://user-images.githubusercontent.com/18424138/75892654-b0a70180-5dff-11ea-8727-ecfc72c294ea.png">

## Expected behaviour
The following tumour-related fields should only need to be completed only if tumour_normal_designation is Tumour. these should have dependency tags.

pathological_tumour_staging_system
pathological_T_category
pathological_N_category
pathological_M_category
pathological_stage_group
tumour_grading_system
tumour_grade
percent_tumour_cells
percent_proliferating_cells
percent_stromal_cells
percent_necrosis

@hknahal these 
pathological_T_category
pathological_N_category
pathological_M_category are dependent on pathological_tumour_staging_system already...so not sure if those need to be dependent on tumour_normal_designation too.

**Comment by kcullion** [comment]
@hknahal I feel like this is higher priority than this: https://github.com/icgc-argo/argo-dictionary/issues/55
What do you think?

**Comment by hknahal** [comment]
@kcullion I agree

**Comment by kcullion** [comment]
Ok thanks @hknahal is this something you are working on? Or should we ask Wajiha or Ann

**Comment by hknahal** [comment]
I haven't started working on this yet, but I'll do it today.

**Comment by wajiha-oicr** [comment]
@hknahal @rosibaj @kcullion  I'm checking prod and didn't notice the note for these two fields:

- tumour_grade
- pathological_stage_group

**Comment by hknahal** [comment]
@wajiha-oicr I left the note out since `tumour_grade` is dependent on `tumour_grading_system` which has a dependency on specimen being a tumour. So `tumour_grade` can't be submitted unless `tumour_grading_system` is submitted, but `tumour_grading_system` can only be filled in if the specimen is tumour. Same with `pathological_stage_group` (it depends on `pathological_staging_system` which depends on the specimen being a tumour). But I can see how in the dictionary it may look inconsistent. I can add a note in for both fields - what do you think @wajiha-oicr @rosibaj @kcullion ?

**Comment by wajiha-oicr** [comment]
I understand what you mean, interested to hear what @rosibaj thinks.

The fields are still considered required though, as per https://github.com/icgc-argo/argo-dictionary/issues/54. So the system will give a user an error if they don't provide these values if the corresponding specimen was labeled as 'tumour'.

**Comment by rosibaj** [comment]
@hknahal @wajiha-oicr i think we should make a note something like this:

`This field depends on the selected tumour grading system, and is only required if the specimen is a tumour.`

**Comment by hknahal** [comment]
Good point @wajiha-oicr  I'll add the same note I did for the other fields.

**Comment by rosibaj** [comment]
@hknahal did you make the change mentioned above in the dictinoary?

**Comment by hknahal** [comment]
@rosibaj Yes, it was completed. I updated the note section for `pathological_stage_group` (see [here](https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/specimen.json#L115)) and `tumour_grade` (see [here](https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/specimen.json#L236))

**Comment by rosibaj** [comment]
@hknahal ok cool!  i wasn't sure for which fields and couldn't find he attached pr! thanks for confirming.

**Comment by hknahal** [comment]
@rosibaj I think it was this one: https://github.com/icgc-argo/argo-dictionary/pull/66
