### ISSUE TITLE
Error suggestion for specimen requiring donor file

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-dictionary#62]
I was confused at what the last two errors meant
<img width="1244" alt="Screen Shot 2020-03-06 at 12 48 52 PM" src="https://user-images.githubusercontent.com/18424138/76108943-83965280-5fa9-11ea-92ad-9559e2b715ca.png">

Suggestion to change:
[specimen_acquisition_interval] requires [donor.vital_status], [donor.survival_time] in order to complete validation. Please upload data for all fields in this clinical data submission.

to
**specimen_acquisition_interval requires vital_status for this donor in order to complete validation. Please upload donor data for this specimen using the donor.tsv file.**

Wondering if we say "and survival_time" in this error as for donors that are alive, they don't require survival time

if so we can write: 
**specimen_acquisition_interval requires vital_status and survival_time (for deceased donors) in order to complete validation. Please upload donor data for this specimen using the donor.tsv file.**

**Comment by rosibaj** [comment]
@kcullion there is an issue with your suggested error change; its not actually accurate - i also think its a bit complicated to know which error to say whether donor is alive or not.  How do you feel about this instead:
```
[specimen_acquisition_interval] requires all of these fields to have valid values 
in order to complete validation:
- [donor.vital_status]
- [donor.survival_time]  

Please upload data for all fields in this clinical data submission.
````

**Comment by kcullion** [comment]
@rosibaj Should we mention they are in the donor file though?
Like it could be as general as:
specimen_acquisition_interval requires vital_status for this donor in order to complete validation. Please upload donor data for this specimen using the donor.tsv file.

Then if they don't put in the survival time in that field when value=Deceased, then they will get another error in this step.

I also removed the [ ] brackets around the field name as other errors don't have that.
