### ISSUE TITLE
Need regex example on Cancer Type Code

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#67]
![image](https://user-images.githubusercontent.com/15824252/76344304-ba38d980-62d7-11ea-9f16-54c156ece38b.png)

**Comment by wajiha-oicr** [comment]
@rosibaj (also @joneubank ) so as we briefly discussed in slack, from https://icd.who.int/browse10/2016/en#/II it appeared that all neoplasm classifications ranged from (C00-D48).

We said for the cancer type code field we're only going to only allow codes starting with `C`.

(By excluding D, we're excluding codes for `In situ neoplasms`, `Benign neoplasms`, and `Neoplasms of uncertain or unknown behaviour`). Is that okay?

**Comment by rosibaj** [comment]
@wajiha-oicr I do not see this on : https://docs.qa.argo.cancercollaboratory.org/dictionary/  

has this been released to qa?

**Comment by wajiha-oicr** [comment]
the dictionary migration was been done to QA. I'm not sure how the docs site gets pointed to the latest dictionary though. Is there another step?

**Comment by rosibaj** [comment]
@joneubank @ciaranschutte ^ we need to rebuild dictionary.  @ciaranschutte are you doing this today?

**Comment by ciaranschutte** [comment]
@rosibaj I can do this today

**Comment by rosibaj** [comment]
will be visible in dictionary after prod release

**Comment by rosibaj** [comment]
confirmed on prod dictionary release lgtm
