### ISSUE TITLE
Need codelist for T, N and M values

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#73]
## Detailed Description
We need a codelist for all the T, N and M values when the cancer staging system is AJCC. Some cancer types only allow certain values for T. For example, breast cancer allows `Tis` but other cancer types do not.

**Comment by rosibaj** [comment]
@hknahal the GDC already has these as codelists:  can we just use those:
https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=diagnosis&anchor=ajcc_pathologic_t

**Comment by hknahal** [comment]
@rosibaj Sounds good. I'll start a wiki page to document this. I believe the GDC codelist is a general list (ie. it doesn't differentiate between different AJCC versions), but a good starting point. For example, "MX" was eliminated in AJCC 7th ed. (no longer considered valid), but it exists in AJCC 6th ed.

**Comment by hknahal** [comment]
TNM staging by cancer type: https://docs.google.com/spreadsheets/d/1xaJnh9JF9Qq0Rg3WlDTDUxkYZR3gvsSSfw4uaGq6fXk/edit?usp=sharing

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
