### ISSUE TITLE
🐛 Fix codelist for tumour grades and add update tumour grading systems

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#74]
## Describe the bug
The existing codelist for Gleason values (ie. when tumour_grading_system is gleason) contains dashes (ie. gleason 2–6). When a data submitter copies and pastes a gleason value from the browser to an  excel file, the dash renders as a special character.

## Error during clinical validation:
<img width="1192" alt="Screen Shot 2020-03-24 at 3 33 41 PM" src="https://user-images.githubusercontent.com/4992044/77470072-79b48200-6de6-11ea-9ed8-dd6fd4ef51ea.png">

## Solution
Consider replacing existing codelist with gleason grade groups which don't contain dashes. Can provide mapping information between grade groups and scores in "Notes" section:

**Comment by hknahal** [comment]
Currently adding additional tumour grading systems:

- Two grade system
- Three grade system
- Gleason
- FNCLCC grading system
- Scarff-bloom-richardson grading system
- Grading for GISTs
- Nuclear grade (for breast ductal carcinoma in situ
- Grading for brain cancer",
- Grading for malignant melanoma of the conjunctiva
- Grading for malignant melanoma of the uvea
- ISUP grading for renal cell carcinoma
- Grading for lymphoid neoplasms
- Grading for follicular lymphomas

**Comment by hknahal** [comment]
In addition to updating Gleason tumour grades, added/updated following tumour grading systems:

Two-tier grade system
Three-tier grading system
Four-tier grading system
Grading system for GISTs
Grading system for GNETs
ISUP grading system
WHO grading system for CNS tumours
FNCLCC grading system
Gleason grade group system
Scarff-Bloom-Richardson grading system
Nuclear grading for DCIS

Summary: https://docs.google.com/spreadsheets/d/1uBGaZyyX5_2ZzQCD9Qbv64KG71D72tIYb6Clb1vLSAY/edit?usp=sharing
PR: https://github.com/icgc-argo/argo-dictionary/pull/120

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
