### ISSUE TITLE
🐛 Correct dosage units used for children < 10kg

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#75]
## Describe the bug
For children under 10kg, the dosing of chemotherapeutic drugs is dosed according to body weight instead of body surface area. 

## Fix
Need to update codelist to mg/kg [here](https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/chemotherapy.json#L70) and [here](https://github.com/icgc-argo/argo-dictionary/blob/master/schemas/hormone_therapy.json#L69)

**Comment by rosibaj** [comment]
fixed in this pr: https://github.com/icgc-argo/argo-dictionary/pull/76

**Comment by rosibaj** [comment]
confirmed on prod dictionary release - lgtm
