### ISSUE TITLE
Add new extended field in Primary Diagnosis table "basis_of_diagnosis"

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#82]
## Description
A few projects have asked what the primary diagnosis should be since they use different methods to determine the diagnosis. In reality, the primary diagnosis can be made on the basis of different methods and each project/cancer type may use different ways to determine the diagnosis (ie. imaging or biopsy or clinical only etc.). 

## Implementation
Propose adding a new extended (optional) field called "**basis_of_diagnosis**"  in the `Primary Diagnosis` table which will let data submitters specify the method of primary diagnosis. This field will consist of a controlled vocabulary recommended by the IARC and WHO:

![WHO_IARC_basis_of_diagnosis](https://user-images.githubusercontent.com/4992044/77800524-55a6aa00-704d-11ea-9961-445190968dd7.jpg)

Both WHO (see see https://apps.who.int/iris/bitstream/handle/10665/96612/9789241548496_eng.pdf page 27, Table 26) and the ENCR (European Network of Cancer Registries) recommend this codelist (see [here](https://www.encr.eu/sites/default/files/pdf/basisd.pdf)). Only the most valid basis of diagnosis is required (ie. only need to submit one value for this clinical field). The "Notes" section will contain details and a link to WHO/IARC for reference.

**Comment by rosibaj** [comment]
@hlminh2000 we can use this ticket to make sure the hotfix gets applied back to QA in docs at end of release

**Comment by rosibaj** [comment]
@hlminh2000 @ciaranschutte was holding this ticket  to make sure the hotfix got merged back - has that been done?

**Comment by rosibaj** [comment]
Deployed to production, dictionary version `0.10`
