### ISSUE TITLE
Add an extended field for weight in Follow up table

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-dictionary#92]
## Description:

We currently ask for the patient's "weight" in the Donor level. This would be baseline weight, but it would also be good to have the patient's weight at followup since it can change:

Use case from data submitter for PACA-CA project:

Email from Rajshree:

> The weight of patients may vary substantially from diagnosis till resection. Neoadjuvant chemotherapy, if given prior to surgery, can result in significant appetite changes; biliary obstruction due to a pancreatic mass can alter eating habits as can cause nausea and vomiting. So the weight can drop significantly and is monitored at each clinic visit

## Implementation
Will add a new optional field called "weight_at_followup" in the Followup table

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-dictionary/pull/93 added here
