### ISSUE TITLE
Beta Feedback: Note for each program_id

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-dictionary#98]
Beta testers are confused as to where they find their program_id.

For each program_id entry in the dictionary, please add the following note:

`This is the unique id that is assigned to your program. When you are logged in, the program_id can be found in the top title bar of your Submission Dashboard. PACA-AU is an example of a program_id.`

**Comment by rosibaj** [comment]
This was talked about and we do not want to implement this way in the whole dictionary.
