### ISSUE TITLE
Beta Feedback: Alphabetize permissible values 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-dictionary#99]
Beta feedback: would be easier to read the values if they were in alphabetic order.

Alphabetize permissible values for all value lists in the dictionary

**Comment by rosibaj** [comment]
sample_registration was missed - that was inlcuded in this PR: https://github.com/icgc-argo/argo-dictionary/pull/158 

looks like script values are still not alphabetized

**Comment by rosibaj** [comment]
Tested on staging with dictionary 0.14, migrated to prod on dictionary 0.14
